/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppDeployment,
  AppDeploymentsResponse,
  CreateDeploymentRequest,
  DeploymentFromCIInput,
  ProblemDetails,
} from '../models/index';

export interface CancelAppDeploymentRequest {
    id: number;
}

export interface CreateAppDeploymentRequest {
    createDeploymentRequest: CreateDeploymentRequest;
}

export interface CreateAppDeploymentFromCiRequest {
    deploymentFromCIInput: DeploymentFromCIInput;
}

export interface GetAppDeploymentRequest {
    id: number;
}

export interface ListAppDeploymentsRequest {
    appInstanceId: number;
    page?: number;
    pageSize?: number;
}

export interface RedeployAppDeploymentRequest {
    id: number;
}

/**
 * AppDeploymentsApi - interface
 * 
 * @export
 * @interface AppDeploymentsApiInterface
 */
export interface AppDeploymentsApiInterface {
    /**
     * Cancels an active deployment and returns its updated state.
     * @summary Cancel deployment
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppDeploymentsApiInterface
     */
    cancelAppDeploymentRaw(requestParameters: CancelAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>>;

    /**
     * Cancels an active deployment and returns its updated state.
     * Cancel deployment
     */
    cancelAppDeployment(requestParameters: CancelAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment>;

    /**
     * Creates a deployment and returns the created resource.
     * @summary Create deployment
     * @param {CreateDeploymentRequest} createDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppDeploymentsApiInterface
     */
    createAppDeploymentRaw(requestParameters: CreateAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>>;

    /**
     * Creates a deployment and returns the created resource.
     * Create deployment
     */
    createAppDeployment(requestParameters: CreateAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment>;

    /**
     * Creates a deployment from a CI workflow request.
     * @summary Create deployment from CI
     * @param {DeploymentFromCIInput} deploymentFromCIInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppDeploymentsApiInterface
     */
    createAppDeploymentFromCiRaw(requestParameters: CreateAppDeploymentFromCiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>>;

    /**
     * Creates a deployment from a CI workflow request.
     * Create deployment from CI
     */
    createAppDeploymentFromCi(requestParameters: CreateAppDeploymentFromCiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment>;

    /**
     * Returns the deployment identified by the request path.
     * @summary Get deployment
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppDeploymentsApiInterface
     */
    getAppDeploymentRaw(requestParameters: GetAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>>;

    /**
     * Returns the deployment identified by the request path.
     * Get deployment
     */
    getAppDeployment(requestParameters: GetAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment>;

    /**
     * Returns app deployments matching the request filters.
     * @summary List app deployments
     * @param {number} appInstanceId 
     * @param {number} [page] Page number, defaults to 1
     * @param {number} [pageSize] Page size, defaults to 30
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppDeploymentsApiInterface
     */
    listAppDeploymentsRaw(requestParameters: ListAppDeploymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeploymentsResponse>>;

    /**
     * Returns app deployments matching the request filters.
     * List app deployments
     */
    listAppDeployments(requestParameters: ListAppDeploymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeploymentsResponse>;

    /**
     * Creates a redeployment task for an existing deployment.
     * @summary Redeploy deployment
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppDeploymentsApiInterface
     */
    redeployAppDeploymentRaw(requestParameters: RedeployAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>>;

    /**
     * Creates a redeployment task for an existing deployment.
     * Redeploy deployment
     */
    redeployAppDeployment(requestParameters: RedeployAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment>;

}

/**
 * 
 */
export class AppDeploymentsApi extends runtime.BaseAPI implements AppDeploymentsApiInterface {

    /**
     * Cancels an active deployment and returns its updated state.
     * Cancel deployment
     */
    async cancelAppDeploymentRaw(requestParameters: CancelAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelAppDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-deployments/{id}/actions/cancel`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Cancels an active deployment and returns its updated state.
     * Cancel deployment
     */
    async cancelAppDeployment(requestParameters: CancelAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment> {
        const response = await this.cancelAppDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a deployment and returns the created resource.
     * Create deployment
     */
    async createAppDeploymentRaw(requestParameters: CreateAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>> {
        if (requestParameters['createDeploymentRequest'] == null) {
            throw new runtime.RequiredError(
                'createDeploymentRequest',
                'Required parameter "createDeploymentRequest" was null or undefined when calling createAppDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-deployments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createDeploymentRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a deployment and returns the created resource.
     * Create deployment
     */
    async createAppDeployment(requestParameters: CreateAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment> {
        const response = await this.createAppDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a deployment from a CI workflow request.
     * Create deployment from CI
     */
    async createAppDeploymentFromCiRaw(requestParameters: CreateAppDeploymentFromCiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>> {
        if (requestParameters['deploymentFromCIInput'] == null) {
            throw new runtime.RequiredError(
                'deploymentFromCIInput',
                'Required parameter "deploymentFromCIInput" was null or undefined when calling createAppDeploymentFromCi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // ciAccessTokenHeader authentication
        }

        const response = await this.request({
            path: `/app-deployments/from-ci`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['deploymentFromCIInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a deployment from a CI workflow request.
     * Create deployment from CI
     */
    async createAppDeploymentFromCi(requestParameters: CreateAppDeploymentFromCiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment> {
        const response = await this.createAppDeploymentFromCiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the deployment identified by the request path.
     * Get deployment
     */
    async getAppDeploymentRaw(requestParameters: GetAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAppDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-deployments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the deployment identified by the request path.
     * Get deployment
     */
    async getAppDeployment(requestParameters: GetAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment> {
        const response = await this.getAppDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns app deployments matching the request filters.
     * List app deployments
     */
    async listAppDeploymentsRaw(requestParameters: ListAppDeploymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeploymentsResponse>> {
        if (requestParameters['appInstanceId'] == null) {
            throw new runtime.RequiredError(
                'appInstanceId',
                'Required parameter "appInstanceId" was null or undefined when calling listAppDeployments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['appInstanceId'] != null) {
            queryParameters['appInstanceId'] = requestParameters['appInstanceId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-deployments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns app deployments matching the request filters.
     * List app deployments
     */
    async listAppDeployments(requestParameters: ListAppDeploymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeploymentsResponse> {
        const response = await this.listAppDeploymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a redeployment task for an existing deployment.
     * Redeploy deployment
     */
    async redeployAppDeploymentRaw(requestParameters: RedeployAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppDeployment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling redeployAppDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-deployments/{id}/redeploy`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a redeployment task for an existing deployment.
     * Redeploy deployment
     */
    async redeployAppDeployment(requestParameters: RedeployAppDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppDeployment> {
        const response = await this.redeployAppDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
