/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppInstance,
  NewAppInstanceInput,
  OperationResult,
  UpdateTitleRequest,
} from '../models/index';
import {
    AppInstanceFromJSON,
    AppInstanceToJSON,
    NewAppInstanceInputFromJSON,
    NewAppInstanceInputToJSON,
    OperationResultFromJSON,
    OperationResultToJSON,
    UpdateTitleRequestFromJSON,
    UpdateTitleRequestToJSON,
} from '../models/index';

export interface AppInstancesByNameAppNameInstanceNameGetRequest {
    appName: string;
    instanceName: string;
    orgId: number;
}

export interface AppInstancesGetRequest {
    orgId: number;
    projectIds?: string;
    appId?: number;
    clusterId?: number;
    clusterApp?: boolean;
}

export interface AppInstancesIdDeleteRequest {
    id: number;
    force?: boolean;
}

export interface AppInstancesIdGetRequest {
    id: number;
}

export interface AppInstancesIdPutRequest {
    id: number;
    updateTitleRequest: UpdateTitleRequest;
}

export interface AppInstancesPostRequest {
    newAppInstanceInput: NewAppInstanceInput;
}

/**
 * AppInstancesApi - interface
 * 
 * @export
 * @interface AppInstancesApiInterface
 */
export interface AppInstancesApiInterface {
    /**
     * 
     * @summary Get app instance by app and instance name
     * @param {string} appName 
     * @param {string} instanceName 
     * @param {number} orgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppInstancesApiInterface
     */
    appInstancesByNameAppNameInstanceNameGetRaw(requestParameters: AppInstancesByNameAppNameInstanceNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>>;

    /**
     * Get app instance by app and instance name
     */
    appInstancesByNameAppNameInstanceNameGet(requestParameters: AppInstancesByNameAppNameInstanceNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance>;

    /**
     * 
     * @summary List app instances
     * @param {number} orgId 
     * @param {string} [projectIds] Comma-separated project ids
     * @param {number} [appId] 
     * @param {number} [clusterId] 
     * @param {boolean} [clusterApp] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppInstancesApiInterface
     */
    appInstancesGetRaw(requestParameters: AppInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppInstance>>>;

    /**
     * List app instances
     */
    appInstancesGet(requestParameters: AppInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppInstance>>;

    /**
     * 
     * @summary Delete app instance
     * @param {number} id 
     * @param {boolean} [force] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppInstancesApiInterface
     */
    appInstancesIdDeleteRaw(requestParameters: AppInstancesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Delete app instance
     */
    appInstancesIdDelete(requestParameters: AppInstancesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * 
     * @summary Get app instance
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppInstancesApiInterface
     */
    appInstancesIdGetRaw(requestParameters: AppInstancesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>>;

    /**
     * Get app instance
     */
    appInstancesIdGet(requestParameters: AppInstancesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance>;

    /**
     * 
     * @summary Update app instance
     * @param {number} id 
     * @param {UpdateTitleRequest} updateTitleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppInstancesApiInterface
     */
    appInstancesIdPutRaw(requestParameters: AppInstancesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>>;

    /**
     * Update app instance
     */
    appInstancesIdPut(requestParameters: AppInstancesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance>;

    /**
     * 
     * @summary Create app instance
     * @param {NewAppInstanceInput} newAppInstanceInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppInstancesApiInterface
     */
    appInstancesPostRaw(requestParameters: AppInstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>>;

    /**
     * Create app instance
     */
    appInstancesPost(requestParameters: AppInstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance>;

}

/**
 * 
 */
export class AppInstancesApi extends runtime.BaseAPI implements AppInstancesApiInterface {

    /**
     * Get app instance by app and instance name
     */
    async appInstancesByNameAppNameInstanceNameGetRaw(requestParameters: AppInstancesByNameAppNameInstanceNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>> {
        if (requestParameters['appName'] == null) {
            throw new runtime.RequiredError(
                'appName',
                'Required parameter "appName" was null or undefined when calling appInstancesByNameAppNameInstanceNameGet().'
            );
        }

        if (requestParameters['instanceName'] == null) {
            throw new runtime.RequiredError(
                'instanceName',
                'Required parameter "instanceName" was null or undefined when calling appInstancesByNameAppNameInstanceNameGet().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling appInstancesByNameAppNameInstanceNameGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-instances/by-name/{appName}/{instanceName}`.replace(`{${"appName"}}`, encodeURIComponent(String(requestParameters['appName']))).replace(`{${"instanceName"}}`, encodeURIComponent(String(requestParameters['instanceName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppInstanceFromJSON(jsonValue));
    }

    /**
     * Get app instance by app and instance name
     */
    async appInstancesByNameAppNameInstanceNameGet(requestParameters: AppInstancesByNameAppNameInstanceNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance> {
        const response = await this.appInstancesByNameAppNameInstanceNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List app instances
     */
    async appInstancesGetRaw(requestParameters: AppInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppInstance>>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling appInstancesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        if (requestParameters['projectIds'] != null) {
            queryParameters['projectIds'] = requestParameters['projectIds'];
        }

        if (requestParameters['appId'] != null) {
            queryParameters['appId'] = requestParameters['appId'];
        }

        if (requestParameters['clusterId'] != null) {
            queryParameters['clusterId'] = requestParameters['clusterId'];
        }

        if (requestParameters['clusterApp'] != null) {
            queryParameters['clusterApp'] = requestParameters['clusterApp'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-instances`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppInstanceFromJSON));
    }

    /**
     * List app instances
     */
    async appInstancesGet(requestParameters: AppInstancesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppInstance>> {
        const response = await this.appInstancesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete app instance
     */
    async appInstancesIdDeleteRaw(requestParameters: AppInstancesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appInstancesIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-instances/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationResultFromJSON(jsonValue));
    }

    /**
     * Delete app instance
     */
    async appInstancesIdDelete(requestParameters: AppInstancesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.appInstancesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get app instance
     */
    async appInstancesIdGetRaw(requestParameters: AppInstancesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appInstancesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-instances/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppInstanceFromJSON(jsonValue));
    }

    /**
     * Get app instance
     */
    async appInstancesIdGet(requestParameters: AppInstancesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance> {
        const response = await this.appInstancesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update app instance
     */
    async appInstancesIdPutRaw(requestParameters: AppInstancesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appInstancesIdPut().'
            );
        }

        if (requestParameters['updateTitleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTitleRequest',
                'Required parameter "updateTitleRequest" was null or undefined when calling appInstancesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-instances/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTitleRequestToJSON(requestParameters['updateTitleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppInstanceFromJSON(jsonValue));
    }

    /**
     * Update app instance
     */
    async appInstancesIdPut(requestParameters: AppInstancesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance> {
        const response = await this.appInstancesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create app instance
     */
    async appInstancesPostRaw(requestParameters: AppInstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInstance>> {
        if (requestParameters['newAppInstanceInput'] == null) {
            throw new runtime.RequiredError(
                'newAppInstanceInput',
                'Required parameter "newAppInstanceInput" was null or undefined when calling appInstancesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-instances`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewAppInstanceInputToJSON(requestParameters['newAppInstanceInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppInstanceFromJSON(jsonValue));
    }

    /**
     * Create app instance
     */
    async appInstancesPost(requestParameters: AppInstancesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInstance> {
        const response = await this.appInstancesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
