/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppRoute,
  NewAppRouteInput,
  OperationResult,
  UpdateAppRouteInput,
} from '../models/index';
import {
    AppRouteFromJSON,
    AppRouteToJSON,
    NewAppRouteInputFromJSON,
    NewAppRouteInputToJSON,
    OperationResultFromJSON,
    OperationResultToJSON,
    UpdateAppRouteInputFromJSON,
    UpdateAppRouteInputToJSON,
} from '../models/index';

export interface AppRoutesGetRequest {
    appInstanceId: number;
}

export interface AppRoutesIdDeleteRequest {
    id: number;
}

export interface AppRoutesIdGetRequest {
    id: number;
}

export interface AppRoutesIdPutRequest {
    id: number;
    updateAppRouteInput: UpdateAppRouteInput;
}

export interface AppRoutesPostRequest {
    newAppRouteInput: NewAppRouteInput;
}

/**
 * AppRoutesApi - interface
 * 
 * @export
 * @interface AppRoutesApiInterface
 */
export interface AppRoutesApiInterface {
    /**
     * 
     * @summary List app routes
     * @param {number} appInstanceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppRoutesApiInterface
     */
    appRoutesGetRaw(requestParameters: AppRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppRoute>>>;

    /**
     * List app routes
     */
    appRoutesGet(requestParameters: AppRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppRoute>>;

    /**
     * 
     * @summary Delete app route
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppRoutesApiInterface
     */
    appRoutesIdDeleteRaw(requestParameters: AppRoutesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Delete app route
     */
    appRoutesIdDelete(requestParameters: AppRoutesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * 
     * @summary Get app route
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppRoutesApiInterface
     */
    appRoutesIdGetRaw(requestParameters: AppRoutesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoute>>;

    /**
     * Get app route
     */
    appRoutesIdGet(requestParameters: AppRoutesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoute>;

    /**
     * 
     * @summary Update app route
     * @param {number} id 
     * @param {UpdateAppRouteInput} updateAppRouteInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppRoutesApiInterface
     */
    appRoutesIdPutRaw(requestParameters: AppRoutesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoute>>;

    /**
     * Update app route
     */
    appRoutesIdPut(requestParameters: AppRoutesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoute>;

    /**
     * 
     * @summary Create app route
     * @param {NewAppRouteInput} newAppRouteInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppRoutesApiInterface
     */
    appRoutesPostRaw(requestParameters: AppRoutesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoute>>;

    /**
     * Create app route
     */
    appRoutesPost(requestParameters: AppRoutesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoute>;

}

/**
 * 
 */
export class AppRoutesApi extends runtime.BaseAPI implements AppRoutesApiInterface {

    /**
     * List app routes
     */
    async appRoutesGetRaw(requestParameters: AppRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppRoute>>> {
        if (requestParameters['appInstanceId'] == null) {
            throw new runtime.RequiredError(
                'appInstanceId',
                'Required parameter "appInstanceId" was null or undefined when calling appRoutesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['appInstanceId'] != null) {
            queryParameters['appInstanceId'] = requestParameters['appInstanceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-routes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppRouteFromJSON));
    }

    /**
     * List app routes
     */
    async appRoutesGet(requestParameters: AppRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppRoute>> {
        const response = await this.appRoutesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete app route
     */
    async appRoutesIdDeleteRaw(requestParameters: AppRoutesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appRoutesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-routes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationResultFromJSON(jsonValue));
    }

    /**
     * Delete app route
     */
    async appRoutesIdDelete(requestParameters: AppRoutesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.appRoutesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get app route
     */
    async appRoutesIdGetRaw(requestParameters: AppRoutesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoute>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appRoutesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-routes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRouteFromJSON(jsonValue));
    }

    /**
     * Get app route
     */
    async appRoutesIdGet(requestParameters: AppRoutesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoute> {
        const response = await this.appRoutesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update app route
     */
    async appRoutesIdPutRaw(requestParameters: AppRoutesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoute>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appRoutesIdPut().'
            );
        }

        if (requestParameters['updateAppRouteInput'] == null) {
            throw new runtime.RequiredError(
                'updateAppRouteInput',
                'Required parameter "updateAppRouteInput" was null or undefined when calling appRoutesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-routes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAppRouteInputToJSON(requestParameters['updateAppRouteInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRouteFromJSON(jsonValue));
    }

    /**
     * Update app route
     */
    async appRoutesIdPut(requestParameters: AppRoutesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoute> {
        const response = await this.appRoutesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create app route
     */
    async appRoutesPostRaw(requestParameters: AppRoutesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoute>> {
        if (requestParameters['newAppRouteInput'] == null) {
            throw new runtime.RequiredError(
                'newAppRouteInput',
                'Required parameter "newAppRouteInput" was null or undefined when calling appRoutesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/app-routes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewAppRouteInputToJSON(requestParameters['newAppRouteInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRouteFromJSON(jsonValue));
    }

    /**
     * Create app route
     */
    async appRoutesPost(requestParameters: AppRoutesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoute> {
        const response = await this.appRoutesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
