/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Backup,
  NewBackupInput,
  OperationResult,
  ProblemDetails,
} from '../models/index';
import {
    BackupFromJSON,
    BackupToJSON,
    NewBackupInputFromJSON,
    NewBackupInputToJSON,
    OperationResultFromJSON,
    OperationResultToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface CreateBackupRequest {
    newBackupInput: NewBackupInput;
}

export interface GetBackupRequest {
    id: number;
}

export interface ListBackupsRequest {
    appInstanceId?: number;
    appServiceId?: number;
    databaseId?: number;
    databaseDbId?: number;
    backupName?: string;
}

/**
 * BackupsApi - interface
 * 
 * @export
 * @interface BackupsApiInterface
 */
export interface BackupsApiInterface {
    /**
     * Creates a backup and returns the created resource.
     * @summary Create backup
     * @param {NewBackupInput} newBackupInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    createBackupRaw(requestParameters: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Creates a backup and returns the created resource.
     * Create backup
     */
    createBackup(requestParameters: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * Returns the backup identified by the request path.
     * @summary Get backup
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    getBackupRaw(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Backup>>;

    /**
     * Returns the backup identified by the request path.
     * Get backup
     */
    getBackup(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Backup>;

    /**
     * Returns backups matching the request filters.
     * @summary List backups
     * @param {number} [appInstanceId] 
     * @param {number} [appServiceId] 
     * @param {number} [databaseId] 
     * @param {number} [databaseDbId] 
     * @param {string} [backupName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Backup>>>;

    /**
     * Returns backups matching the request filters.
     * List backups
     */
    listBackups(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Backup>>;

}

/**
 * 
 */
export class BackupsApi extends runtime.BaseAPI implements BackupsApiInterface {

    /**
     * Creates a backup and returns the created resource.
     * Create backup
     */
    async createBackupRaw(requestParameters: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['newBackupInput'] == null) {
            throw new runtime.RequiredError(
                'newBackupInput',
                'Required parameter "newBackupInput" was null or undefined when calling createBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/backups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewBackupInputToJSON(requestParameters['newBackupInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationResultFromJSON(jsonValue));
    }

    /**
     * Creates a backup and returns the created resource.
     * Create backup
     */
    async createBackup(requestParameters: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.createBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the backup identified by the request path.
     * Get backup
     */
    async getBackupRaw(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Backup>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/backups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupFromJSON(jsonValue));
    }

    /**
     * Returns the backup identified by the request path.
     * Get backup
     */
    async getBackup(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Backup> {
        const response = await this.getBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns backups matching the request filters.
     * List backups
     */
    async listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Backup>>> {
        const queryParameters: any = {};

        if (requestParameters['appInstanceId'] != null) {
            queryParameters['appInstanceId'] = requestParameters['appInstanceId'];
        }

        if (requestParameters['appServiceId'] != null) {
            queryParameters['appServiceId'] = requestParameters['appServiceId'];
        }

        if (requestParameters['databaseId'] != null) {
            queryParameters['databaseId'] = requestParameters['databaseId'];
        }

        if (requestParameters['databaseDbId'] != null) {
            queryParameters['databaseDbId'] = requestParameters['databaseDbId'];
        }

        if (requestParameters['backupName'] != null) {
            queryParameters['backupName'] = requestParameters['backupName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/backups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BackupFromJSON));
    }

    /**
     * Returns backups matching the request filters.
     * List backups
     */
    async listBackups(requestParameters: ListBackupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Backup>> {
        const response = await this.listBackupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
