/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEnvRequest,
  Env,
  ErrorResponse,
  OperationResult,
  UpdateEnvRequest,
} from '../models/index';
import {
    CreateEnvRequestFromJSON,
    CreateEnvRequestToJSON,
    EnvFromJSON,
    EnvToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    OperationResultFromJSON,
    OperationResultToJSON,
    UpdateEnvRequestFromJSON,
    UpdateEnvRequestToJSON,
} from '../models/index';

export interface CreateEnvOperationRequest {
    createEnvRequest: CreateEnvRequest;
}

export interface DeleteEnvRequest {
    id: number;
}

export interface GetEnvRequest {
    id: number;
}

export interface GetEnvByNameRequest {
    name: string;
    orgId?: number;
}

export interface ListEnvsRequest {
    orgId?: number;
}

export interface UpdateEnvOperationRequest {
    id: number;
    updateEnvRequest: UpdateEnvRequest;
}

/**
 * EnvsApi - interface
 * 
 * @export
 * @interface EnvsApiInterface
 */
export interface EnvsApiInterface {
    /**
     * Creates an env and returns the created resource.
     * @summary Create env
     * @param {CreateEnvRequest} createEnvRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvsApiInterface
     */
    createEnvRaw(requestParameters: CreateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>>;

    /**
     * Creates an env and returns the created resource.
     * Create env
     */
    createEnv(requestParameters: CreateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env>;

    /**
     * Deletes the env and returns the operation result.
     * @summary Delete env
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvsApiInterface
     */
    deleteEnvRaw(requestParameters: DeleteEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Deletes the env and returns the operation result.
     * Delete env
     */
    deleteEnv(requestParameters: DeleteEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * Returns the env identified by the request path.
     * @summary Get env
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvsApiInterface
     */
    getEnvRaw(requestParameters: GetEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>>;

    /**
     * Returns the env identified by the request path.
     * Get env
     */
    getEnv(requestParameters: GetEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env>;

    /**
     * Returns the env identified by name.
     * @summary Get env by name
     * @param {string} name 
     * @param {number} [orgId] Optional for API-key requests; defaults to the API key\&#39;s organization. If provided, it must match the key\&#39;s organization.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvsApiInterface
     */
    getEnvByNameRaw(requestParameters: GetEnvByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>>;

    /**
     * Returns the env identified by name.
     * Get env by name
     */
    getEnvByName(requestParameters: GetEnvByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env>;

    /**
     * Returns envs matching the request filters.
     * @summary List envs
     * @param {number} [orgId] Optional for API-key requests; defaults to the API key\&#39;s organization. If provided, it must match the key\&#39;s organization.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvsApiInterface
     */
    listEnvsRaw(requestParameters: ListEnvsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Env>>>;

    /**
     * Returns envs matching the request filters.
     * List envs
     */
    listEnvs(requestParameters: ListEnvsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Env>>;

    /**
     * Updates the env and returns the updated resource.
     * @summary Update env
     * @param {number} id 
     * @param {UpdateEnvRequest} updateEnvRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnvsApiInterface
     */
    updateEnvRaw(requestParameters: UpdateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>>;

    /**
     * Updates the env and returns the updated resource.
     * Update env
     */
    updateEnv(requestParameters: UpdateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env>;

}

/**
 * 
 */
export class EnvsApi extends runtime.BaseAPI implements EnvsApiInterface {

    /**
     * Creates an env and returns the created resource.
     * Create env
     */
    async createEnvRaw(requestParameters: CreateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>> {
        if (requestParameters['createEnvRequest'] == null) {
            throw new runtime.RequiredError(
                'createEnvRequest',
                'Required parameter "createEnvRequest" was null or undefined when calling createEnv().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/envs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEnvRequestToJSON(requestParameters['createEnvRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvFromJSON(jsonValue));
    }

    /**
     * Creates an env and returns the created resource.
     * Create env
     */
    async createEnv(requestParameters: CreateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env> {
        const response = await this.createEnvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes the env and returns the operation result.
     * Delete env
     */
    async deleteEnvRaw(requestParameters: DeleteEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEnv().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/envs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationResultFromJSON(jsonValue));
    }

    /**
     * Deletes the env and returns the operation result.
     * Delete env
     */
    async deleteEnv(requestParameters: DeleteEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.deleteEnvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the env identified by the request path.
     * Get env
     */
    async getEnvRaw(requestParameters: GetEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEnv().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/envs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvFromJSON(jsonValue));
    }

    /**
     * Returns the env identified by the request path.
     * Get env
     */
    async getEnv(requestParameters: GetEnvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env> {
        const response = await this.getEnvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the env identified by name.
     * Get env by name
     */
    async getEnvByNameRaw(requestParameters: GetEnvByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getEnvByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/envs/by-name/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvFromJSON(jsonValue));
    }

    /**
     * Returns the env identified by name.
     * Get env by name
     */
    async getEnvByName(requestParameters: GetEnvByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env> {
        const response = await this.getEnvByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns envs matching the request filters.
     * List envs
     */
    async listEnvsRaw(requestParameters: ListEnvsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Env>>> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/envs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnvFromJSON));
    }

    /**
     * Returns envs matching the request filters.
     * List envs
     */
    async listEnvs(requestParameters: ListEnvsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Env>> {
        const response = await this.listEnvsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the env and returns the updated resource.
     * Update env
     */
    async updateEnvRaw(requestParameters: UpdateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Env>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEnv().'
            );
        }

        if (requestParameters['updateEnvRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEnvRequest',
                'Required parameter "updateEnvRequest" was null or undefined when calling updateEnv().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/envs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEnvRequestToJSON(requestParameters['updateEnvRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvFromJSON(jsonValue));
    }

    /**
     * Updates the env and returns the updated resource.
     * Update env
     */
    async updateEnv(requestParameters: UpdateEnvOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Env> {
        const response = await this.updateEnvRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
