/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GitRepoUsages,
  OperationResult,
  ProblemDetails,
  UpdateStackFromGitRequest,
} from '../models/index';

export interface GetGitRepoUsagesRequest {
    id: number;
}

export interface UpdateGitRepoFromGitRequest {
    id: number;
    updateStackFromGitRequest: UpdateStackFromGitRequest;
}

/**
 * GitReposApi - interface
 * 
 * @export
 * @interface GitReposApiInterface
 */
export interface GitReposApiInterface {
    /**
     * Returns every service, stack, and provider that shares the Git repository.
     * @summary Get Git repository usages
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitReposApiInterface
     */
    getGitRepoUsagesRaw(requestParameters: GetGitRepoUsagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GitRepoUsages>>;

    /**
     * Returns every service, stack, and provider that shares the Git repository.
     * Get Git repository usages
     */
    getGitRepoUsages(requestParameters: GetGitRepoUsagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GitRepoUsages>;

    /**
     * Starts one parent task that updates every service, stack, and provider sharing the selected repository to the requested ref.
     * @summary Update all Git repository usages
     * @param {number} id 
     * @param {UpdateStackFromGitRequest} updateStackFromGitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitReposApiInterface
     */
    updateGitRepoFromGitRaw(requestParameters: UpdateGitRepoFromGitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Starts one parent task that updates every service, stack, and provider sharing the selected repository to the requested ref.
     * Update all Git repository usages
     */
    updateGitRepoFromGit(requestParameters: UpdateGitRepoFromGitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

}

/**
 * 
 */
export class GitReposApi extends runtime.BaseAPI implements GitReposApiInterface {

    /**
     * Returns every service, stack, and provider that shares the Git repository.
     * Get Git repository usages
     */
    async getGitRepoUsagesRaw(requestParameters: GetGitRepoUsagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GitRepoUsages>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGitRepoUsages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/git-repos/{id}/usages`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns every service, stack, and provider that shares the Git repository.
     * Get Git repository usages
     */
    async getGitRepoUsages(requestParameters: GetGitRepoUsagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GitRepoUsages> {
        const response = await this.getGitRepoUsagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts one parent task that updates every service, stack, and provider sharing the selected repository to the requested ref.
     * Update all Git repository usages
     */
    async updateGitRepoFromGitRaw(requestParameters: UpdateGitRepoFromGitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateGitRepoFromGit().'
            );
        }

        if (requestParameters['updateStackFromGitRequest'] == null) {
            throw new runtime.RequiredError(
                'updateStackFromGitRequest',
                'Required parameter "updateStackFromGitRequest" was null or undefined when calling updateGitRepoFromGit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/git-repos/{id}/actions/update-from-git`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateStackFromGitRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Starts one parent task that updates every service, stack, and provider sharing the selected repository to the requested ref.
     * Update all Git repository usages
     */
    async updateGitRepoFromGit(requestParameters: UpdateGitRepoFromGitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.updateGitRepoFromGitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
