/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Integration,
  NewIntegrationInput,
  OperationResult,
  UpdateIntegrationInput,
} from '../models/index';
import {
    IntegrationFromJSON,
    IntegrationToJSON,
    NewIntegrationInputFromJSON,
    NewIntegrationInputToJSON,
    OperationResultFromJSON,
    OperationResultToJSON,
    UpdateIntegrationInputFromJSON,
    UpdateIntegrationInputToJSON,
} from '../models/index';

export interface IntegrationsByNameNameGetRequest {
    name: string;
    orgId: number;
}

export interface IntegrationsGetRequest {
    orgId: number;
    projectIds?: string;
    labels?: string;
}

export interface IntegrationsIdDeleteRequest {
    id: number;
}

export interface IntegrationsIdPutRequest {
    id: number;
    updateIntegrationInput: UpdateIntegrationInput;
}

export interface IntegrationsPostRequest {
    newIntegrationInput: NewIntegrationInput;
}

/**
 * IntegrationsApi - interface
 * 
 * @export
 * @interface IntegrationsApiInterface
 */
export interface IntegrationsApiInterface {
    /**
     * 
     * @summary Get integration by name
     * @param {string} name 
     * @param {number} orgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    integrationsByNameNameGetRaw(requestParameters: IntegrationsByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Get integration by name
     */
    integrationsByNameNameGet(requestParameters: IntegrationsByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

    /**
     * 
     * @summary List integrations
     * @param {number} orgId 
     * @param {string} [projectIds] Comma-separated project ids
     * @param {string} [labels] Comma-separated labels
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    integrationsGetRaw(requestParameters: IntegrationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Integration>>>;

    /**
     * List integrations
     */
    integrationsGet(requestParameters: IntegrationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Integration>>;

    /**
     * 
     * @summary Delete integration
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    integrationsIdDeleteRaw(requestParameters: IntegrationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Delete integration
     */
    integrationsIdDelete(requestParameters: IntegrationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * 
     * @summary Update integration
     * @param {number} id 
     * @param {UpdateIntegrationInput} updateIntegrationInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    integrationsIdPutRaw(requestParameters: IntegrationsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Update integration
     */
    integrationsIdPut(requestParameters: IntegrationsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

    /**
     * 
     * @summary Create integration
     * @param {NewIntegrationInput} newIntegrationInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    integrationsPostRaw(requestParameters: IntegrationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Create integration
     */
    integrationsPost(requestParameters: IntegrationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI implements IntegrationsApiInterface {

    /**
     * Get integration by name
     */
    async integrationsByNameNameGetRaw(requestParameters: IntegrationsByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling integrationsByNameNameGet().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling integrationsByNameNameGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/by-name/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationFromJSON(jsonValue));
    }

    /**
     * Get integration by name
     */
    async integrationsByNameNameGet(requestParameters: IntegrationsByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.integrationsByNameNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List integrations
     */
    async integrationsGetRaw(requestParameters: IntegrationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Integration>>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling integrationsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        if (requestParameters['projectIds'] != null) {
            queryParameters['projectIds'] = requestParameters['projectIds'];
        }

        if (requestParameters['labels'] != null) {
            queryParameters['labels'] = requestParameters['labels'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IntegrationFromJSON));
    }

    /**
     * List integrations
     */
    async integrationsGet(requestParameters: IntegrationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Integration>> {
        const response = await this.integrationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete integration
     */
    async integrationsIdDeleteRaw(requestParameters: IntegrationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling integrationsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationResultFromJSON(jsonValue));
    }

    /**
     * Delete integration
     */
    async integrationsIdDelete(requestParameters: IntegrationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.integrationsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update integration
     */
    async integrationsIdPutRaw(requestParameters: IntegrationsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling integrationsIdPut().'
            );
        }

        if (requestParameters['updateIntegrationInput'] == null) {
            throw new runtime.RequiredError(
                'updateIntegrationInput',
                'Required parameter "updateIntegrationInput" was null or undefined when calling integrationsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateIntegrationInputToJSON(requestParameters['updateIntegrationInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationFromJSON(jsonValue));
    }

    /**
     * Update integration
     */
    async integrationsIdPut(requestParameters: IntegrationsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.integrationsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create integration
     */
    async integrationsPostRaw(requestParameters: IntegrationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['newIntegrationInput'] == null) {
            throw new runtime.RequiredError(
                'newIntegrationInput',
                'Required parameter "newIntegrationInput" was null or undefined when calling integrationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewIntegrationInputToJSON(requestParameters['newIntegrationInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationFromJSON(jsonValue));
    }

    /**
     * Create integration
     */
    async integrationsPost(requestParameters: IntegrationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.integrationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
