/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppAccessProviderOptions,
  Integration,
  IntegrationConfigurationResult,
  IntegrationEnvironmentPolicyInput,
  IntegrationProviderRevisionUpgrade,
  IntegrationScope,
  KubeVersion,
  NewIntegrationInput,
  OperationResult,
  ProblemDetails,
  RemoteGitRepo,
  RemoteGitRepoFilePresence,
  ResolveIntegrationResult,
  SearchIntegrationsInput,
  UpdateIntegrationInput,
  UpgradeIntegrationProviderRevisionInput,
  ValidateAppAccessHostnameInput,
  ValidationResult,
} from '../models/index';

export interface ConfigureIntegrationRequest {
    id: number;
    updateIntegrationInput: UpdateIntegrationInput;
}

export interface CreateIntegrationRequest {
    newIntegrationInput: NewIntegrationInput;
}

export interface DeleteIntegrationRequest {
    id: number;
}

export interface GetAppAccessProviderOptionsRequest {
    id: number;
}

export interface GetIntegrationRequest {
    id: number;
}

export interface GetIntegrationKubeSettingsRequest {
    id: number;
}

export interface GetIntegrationProviderRevisionUpgradeRequest {
    id: number;
}

export interface GetIntegrationRemoteGitRepoFilePresenceRequest {
    id: number;
    remoteGitRepoId: string;
    path: string;
    ref: string;
}

export interface ListIntegrationKubeMachineTypesRequest {
    id: number;
    location: string;
}

export interface ListIntegrationKubeRegionsRequest {
    id: number;
}

export interface ListIntegrationKubeVersionsRequest {
    id: number;
    location: string;
}

export interface ListIntegrationKubeZonesRequest {
    id: number;
}

export interface ListIntegrationRemoteGitRepoBranchesRequest {
    id: number;
    remoteGitRepoId: string;
}

export interface ListIntegrationRemoteGitRepoTagsRequest {
    id: number;
    remoteGitRepoId: string;
}

export interface ListIntegrationRemoteGitReposRequest {
    id: number;
}

export interface ListIntegrationScopesRequest {
    id: number;
}

export interface ListIntegrationStorageBucketsRequest {
    id: number;
}

export interface ListIntegrationStorageClassesRequest {
    id: number;
}

export interface ListIntegrationsRequest {
    orgId?: number;
    projectIds?: string;
    labels?: string;
    envId?: number;
    envType?: ListIntegrationsEnvTypeEnum;
}

export interface ResolveIntegrationRequest {
    newIntegrationInput: NewIntegrationInput;
}

export interface SearchIntegrationsRequest {
    searchIntegrationsInput: SearchIntegrationsInput;
}

export interface TestIntegrationPermissionsRequest {
    id: number;
}

export interface UpdateIntegrationRequest {
    id: number;
    updateIntegrationInput: UpdateIntegrationInput;
}

export interface UpdateIntegrationEnvironmentPolicyRequest {
    id: number;
    integrationEnvironmentPolicyInput: IntegrationEnvironmentPolicyInput;
}

export interface UpgradeIntegrationProviderRevisionRequest {
    id: number;
    upgradeIntegrationProviderRevisionInput: UpgradeIntegrationProviderRevisionInput;
}

export interface ValidateAppAccessHostnameRequest {
    id: number;
    validateAppAccessHostnameInput: ValidateAppAccessHostnameInput;
}

/**
 * IntegrationsApi - interface
 * 
 * @export
 * @interface IntegrationsApiInterface
 */
export interface IntegrationsApiInterface {
    /**
     * Atomically updates integration metadata, adds selected kinds, merges field values, and returns any background activation or permission-test task.
     * @summary Configure integration
     * @param {number} id 
     * @param {UpdateIntegrationInput} updateIntegrationInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    configureIntegrationRaw(requestParameters: ConfigureIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationConfigurationResult>>;

    /**
     * Atomically updates integration metadata, adds selected kinds, merges field values, and returns any background activation or permission-test task.
     * Configure integration
     */
    configureIntegration(requestParameters: ConfigureIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationConfigurationResult>;

    /**
     * Creates an integration and returns the created resource.
     * @summary Create integration
     * @param {NewIntegrationInput} newIntegrationInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    createIntegrationRaw(requestParameters: CreateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Creates an integration and returns the created resource.
     * Create integration
     */
    createIntegration(requestParameters: CreateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

    /**
     * Deletes the integration and returns the operation result.
     * @summary Delete integration
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    deleteIntegrationRaw(requestParameters: DeleteIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Deletes the integration and returns the operation result.
     * Delete integration
     */
    deleteIntegration(requestParameters: DeleteIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * Returns supported app-access modes, scopes, fields, and hostname behavior for the integration.
     * @summary Get app-access provider options
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getAppAccessProviderOptionsRaw(requestParameters: GetAppAccessProviderOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppAccessProviderOptions>>;

    /**
     * Returns supported app-access modes, scopes, fields, and hostname behavior for the integration.
     * Get app-access provider options
     */
    getAppAccessProviderOptions(requestParameters: GetAppAccessProviderOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppAccessProviderOptions>;

    /**
     * Returns the integration identified by the request path.
     * @summary Get integration
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getIntegrationRaw(requestParameters: GetIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Returns the integration identified by the request path.
     * Get integration
     */
    getIntegration(requestParameters: GetIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

    /**
     * Returns the Kubernetes settings identified by the request path.
     * @summary Get Kubernetes settings
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getIntegrationKubeSettingsRaw(requestParameters: GetIntegrationKubeSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns the Kubernetes settings identified by the request path.
     * Get Kubernetes settings
     */
    getIntegrationKubeSettings(requestParameters: GetIntegrationKubeSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Returns the compatibility decision and revision details for upgrading an integration.
     * @summary Preview provider revision upgrade
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getIntegrationProviderRevisionUpgradeRaw(requestParameters: GetIntegrationProviderRevisionUpgradeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationProviderRevisionUpgrade>>;

    /**
     * Returns the compatibility decision and revision details for upgrading an integration.
     * Preview provider revision upgrade
     */
    getIntegrationProviderRevisionUpgrade(requestParameters: GetIntegrationProviderRevisionUpgradeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationProviderRevisionUpgrade>;

    /**
     * Returns whether a file exists at an exact repository ref through the selected Git integration.
     * @summary Check a remote Git repository file
     * @param {number} id 
     * @param {string} remoteGitRepoId 
     * @param {string} path 
     * @param {string} ref 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getIntegrationRemoteGitRepoFilePresenceRaw(requestParameters: GetIntegrationRemoteGitRepoFilePresenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoteGitRepoFilePresence>>;

    /**
     * Returns whether a file exists at an exact repository ref through the selected Git integration.
     * Check a remote Git repository file
     */
    getIntegrationRemoteGitRepoFilePresence(requestParameters: GetIntegrationRemoteGitRepoFilePresenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoteGitRepoFilePresence>;

    /**
     * Returns Kubernetes machine types matching the request filters.
     * @summary List Kubernetes machine types
     * @param {number} id 
     * @param {string} location 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationKubeMachineTypesRaw(requestParameters: ListIntegrationKubeMachineTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>>;

    /**
     * Returns Kubernetes machine types matching the request filters.
     * List Kubernetes machine types
     */
    listIntegrationKubeMachineTypes(requestParameters: ListIntegrationKubeMachineTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>>;

    /**
     * Returns Kubernetes regions matching the request filters.
     * @summary List Kubernetes regions
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationKubeRegionsRaw(requestParameters: ListIntegrationKubeRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>>;

    /**
     * Returns Kubernetes regions matching the request filters.
     * List Kubernetes regions
     */
    listIntegrationKubeRegions(requestParameters: ListIntegrationKubeRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>>;

    /**
     * Returns Kubernetes versions matching the request filters.
     * @summary List Kubernetes versions
     * @param {number} id 
     * @param {string} location 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationKubeVersionsRaw(requestParameters: ListIntegrationKubeVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KubeVersion>>>;

    /**
     * Returns Kubernetes versions matching the request filters.
     * List Kubernetes versions
     */
    listIntegrationKubeVersions(requestParameters: ListIntegrationKubeVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KubeVersion>>;

    /**
     * Returns Kubernetes zones matching the request filters.
     * @summary List Kubernetes zones
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationKubeZonesRaw(requestParameters: ListIntegrationKubeZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>>;

    /**
     * Returns Kubernetes zones matching the request filters.
     * List Kubernetes zones
     */
    listIntegrationKubeZones(requestParameters: ListIntegrationKubeZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>>;

    /**
     * Returns remote Git repository branches matching the request filters.
     * @summary List remote Git repository branches
     * @param {number} id 
     * @param {string} remoteGitRepoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationRemoteGitRepoBranchesRaw(requestParameters: ListIntegrationRemoteGitRepoBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Returns remote Git repository branches matching the request filters.
     * List remote Git repository branches
     */
    listIntegrationRemoteGitRepoBranches(requestParameters: ListIntegrationRemoteGitRepoBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Returns remote Git repository tags matching the request filters.
     * @summary List remote Git repository tags
     * @param {number} id 
     * @param {string} remoteGitRepoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationRemoteGitRepoTagsRaw(requestParameters: ListIntegrationRemoteGitRepoTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Returns remote Git repository tags matching the request filters.
     * List remote Git repository tags
     */
    listIntegrationRemoteGitRepoTags(requestParameters: ListIntegrationRemoteGitRepoTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Returns remote Git repositories matching the request filters.
     * @summary List remote Git repositories
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationRemoteGitReposRaw(requestParameters: ListIntegrationRemoteGitReposRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RemoteGitRepo>>>;

    /**
     * Returns remote Git repositories matching the request filters.
     * List remote Git repositories
     */
    listIntegrationRemoteGitRepos(requestParameters: ListIntegrationRemoteGitReposRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RemoteGitRepo>>;

    /**
     * Returns integration scopes matching the request filters.
     * @summary List integration scopes
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationScopesRaw(requestParameters: ListIntegrationScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IntegrationScope>>>;

    /**
     * Returns integration scopes matching the request filters.
     * List integration scopes
     */
    listIntegrationScopes(requestParameters: ListIntegrationScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IntegrationScope>>;

    /**
     * Returns storage buckets matching the request filters.
     * @summary List storage buckets
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationStorageBucketsRaw(requestParameters: ListIntegrationStorageBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Returns storage buckets matching the request filters.
     * List storage buckets
     */
    listIntegrationStorageBuckets(requestParameters: ListIntegrationStorageBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Returns storage classes matching the request filters.
     * @summary List storage classes
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationStorageClassesRaw(requestParameters: ListIntegrationStorageClassesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Returns storage classes matching the request filters.
     * List storage classes
     */
    listIntegrationStorageClasses(requestParameters: ListIntegrationStorageClassesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Returns integrations matching the request filters.
     * @summary List integrations
     * @param {number} [orgId] Optional for API-key requests; defaults to the API key\&#39;s organization. If provided, it must match the key\&#39;s organization.
     * @param {string} [projectIds] Comma-separated project ids
     * @param {string} [labels] Comma-separated labels
     * @param {number} [envId] Legacy environment entity filter. Use envType.
     * @param {'prod' | 'test' | 'staging' | 'dev' | 'feature'} [envType] Return only integrations allowed for this fixed environment type.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    listIntegrationsRaw(requestParameters: ListIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Integration>>>;

    /**
     * Returns integrations matching the request filters.
     * List integrations
     */
    listIntegrations(requestParameters: ListIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Integration>>;

    /**
     * Reuses an accessible integration when provider, kinds, scope, environment scopes, and credential values match exactly; otherwise creates it.
     * @summary Resolve or create integration
     * @param {NewIntegrationInput} newIntegrationInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    resolveIntegrationRaw(requestParameters: ResolveIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolveIntegrationResult>>;

    /**
     * Reuses an accessible integration when provider, kinds, scope, environment scopes, and credential values match exactly; otherwise creates it.
     * Resolve or create integration
     */
    resolveIntegration(requestParameters: ResolveIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolveIntegrationResult>;

    /**
     * Returns accessible integrations matching structured type, status, label, variable, project, and environment requirements.
     * @summary Search integrations
     * @param {SearchIntegrationsInput} searchIntegrationsInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    searchIntegrationsRaw(requestParameters: SearchIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Integration>>>;

    /**
     * Returns accessible integrations matching structured type, status, label, variable, project, and environment requirements.
     * Search integrations
     */
    searchIntegrations(requestParameters: SearchIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Integration>>;

    /**
     * Starts the provider permission audit configured by the integration\'s provider revision.
     * @summary Test integration permissions
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    testIntegrationPermissionsRaw(requestParameters: TestIntegrationPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Starts the provider permission audit configured by the integration\'s provider revision.
     * Test integration permissions
     */
    testIntegrationPermissions(requestParameters: TestIntegrationPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * Updates the integration and returns the updated resource.
     * @summary Update integration
     * @param {number} id 
     * @param {UpdateIntegrationInput} updateIntegrationInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    updateIntegrationRaw(requestParameters: UpdateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Updates the integration and returns the updated resource.
     * Update integration
     */
    updateIntegration(requestParameters: UpdateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

    /**
     * Updates the associated environment and exact allowed environment scope. Scope reductions that conflict with existing references are rejected.
     * @summary Update integration environment policy
     * @param {number} id 
     * @param {IntegrationEnvironmentPolicyInput} integrationEnvironmentPolicyInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    updateIntegrationEnvironmentPolicyRaw(requestParameters: UpdateIntegrationEnvironmentPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>>;

    /**
     * Updates the associated environment and exact allowed environment scope. Scope reductions that conflict with existing references are rejected.
     * Update integration environment policy
     */
    updateIntegrationEnvironmentPolicy(requestParameters: UpdateIntegrationEnvironmentPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration>;

    /**
     * Upgrades an integration to its eligible provider revision and optionally drops fields removed by the target contract.
     * @summary Upgrade integration provider revision
     * @param {number} id 
     * @param {UpgradeIntegrationProviderRevisionInput} upgradeIntegrationProviderRevisionInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    upgradeIntegrationProviderRevisionRaw(requestParameters: UpgradeIntegrationProviderRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>>;

    /**
     * Upgrades an integration to its eligible provider revision and optionally drops fields removed by the target contract.
     * Upgrade integration provider revision
     */
    upgradeIntegrationProviderRevision(requestParameters: UpgradeIntegrationProviderRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult>;

    /**
     * Validates an app-access hostname against the provider settings of the integration.
     * @summary Validate an app-access hostname
     * @param {number} id 
     * @param {ValidateAppAccessHostnameInput} validateAppAccessHostnameInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    validateAppAccessHostnameRaw(requestParameters: ValidateAppAccessHostnameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationResult>>;

    /**
     * Validates an app-access hostname against the provider settings of the integration.
     * Validate an app-access hostname
     */
    validateAppAccessHostname(requestParameters: ValidateAppAccessHostnameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationResult>;

}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI implements IntegrationsApiInterface {

    /**
     * Atomically updates integration metadata, adds selected kinds, merges field values, and returns any background activation or permission-test task.
     * Configure integration
     */
    async configureIntegrationRaw(requestParameters: ConfigureIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationConfigurationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling configureIntegration().'
            );
        }

        if (requestParameters['updateIntegrationInput'] == null) {
            throw new runtime.RequiredError(
                'updateIntegrationInput',
                'Required parameter "updateIntegrationInput" was null or undefined when calling configureIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/configuration/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateIntegrationInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Atomically updates integration metadata, adds selected kinds, merges field values, and returns any background activation or permission-test task.
     * Configure integration
     */
    async configureIntegration(requestParameters: ConfigureIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationConfigurationResult> {
        const response = await this.configureIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates an integration and returns the created resource.
     * Create integration
     */
    async createIntegrationRaw(requestParameters: CreateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['newIntegrationInput'] == null) {
            throw new runtime.RequiredError(
                'newIntegrationInput',
                'Required parameter "newIntegrationInput" was null or undefined when calling createIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['newIntegrationInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates an integration and returns the created resource.
     * Create integration
     */
    async createIntegration(requestParameters: CreateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.createIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes the integration and returns the operation result.
     * Delete integration
     */
    async deleteIntegrationRaw(requestParameters: DeleteIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Deletes the integration and returns the operation result.
     * Delete integration
     */
    async deleteIntegration(requestParameters: DeleteIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.deleteIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns supported app-access modes, scopes, fields, and hostname behavior for the integration.
     * Get app-access provider options
     */
    async getAppAccessProviderOptionsRaw(requestParameters: GetAppAccessProviderOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppAccessProviderOptions>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAppAccessProviderOptions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/app-access`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns supported app-access modes, scopes, fields, and hostname behavior for the integration.
     * Get app-access provider options
     */
    async getAppAccessProviderOptions(requestParameters: GetAppAccessProviderOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppAccessProviderOptions> {
        const response = await this.getAppAccessProviderOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the integration identified by the request path.
     * Get integration
     */
    async getIntegrationRaw(requestParameters: GetIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the integration identified by the request path.
     * Get integration
     */
    async getIntegration(requestParameters: GetIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.getIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the Kubernetes settings identified by the request path.
     * Get Kubernetes settings
     */
    async getIntegrationKubeSettingsRaw(requestParameters: GetIntegrationKubeSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIntegrationKubeSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/kube-settings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns the Kubernetes settings identified by the request path.
     * Get Kubernetes settings
     */
    async getIntegrationKubeSettings(requestParameters: GetIntegrationKubeSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getIntegrationKubeSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the compatibility decision and revision details for upgrading an integration.
     * Preview provider revision upgrade
     */
    async getIntegrationProviderRevisionUpgradeRaw(requestParameters: GetIntegrationProviderRevisionUpgradeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationProviderRevisionUpgrade>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIntegrationProviderRevisionUpgrade().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integration-provider-revision-upgrades/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the compatibility decision and revision details for upgrading an integration.
     * Preview provider revision upgrade
     */
    async getIntegrationProviderRevisionUpgrade(requestParameters: GetIntegrationProviderRevisionUpgradeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationProviderRevisionUpgrade> {
        const response = await this.getIntegrationProviderRevisionUpgradeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns whether a file exists at an exact repository ref through the selected Git integration.
     * Check a remote Git repository file
     */
    async getIntegrationRemoteGitRepoFilePresenceRaw(requestParameters: GetIntegrationRemoteGitRepoFilePresenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoteGitRepoFilePresence>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIntegrationRemoteGitRepoFilePresence().'
            );
        }

        if (requestParameters['remoteGitRepoId'] == null) {
            throw new runtime.RequiredError(
                'remoteGitRepoId',
                'Required parameter "remoteGitRepoId" was null or undefined when calling getIntegrationRemoteGitRepoFilePresence().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getIntegrationRemoteGitRepoFilePresence().'
            );
        }

        if (requestParameters['ref'] == null) {
            throw new runtime.RequiredError(
                'ref',
                'Required parameter "ref" was null or undefined when calling getIntegrationRemoteGitRepoFilePresence().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['remoteGitRepoId'] != null) {
            queryParameters['remoteGitRepoId'] = requestParameters['remoteGitRepoId'];
        }

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['ref'] != null) {
            queryParameters['ref'] = requestParameters['ref'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/remote-git-repo-file`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns whether a file exists at an exact repository ref through the selected Git integration.
     * Check a remote Git repository file
     */
    async getIntegrationRemoteGitRepoFilePresence(requestParameters: GetIntegrationRemoteGitRepoFilePresenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoteGitRepoFilePresence> {
        const response = await this.getIntegrationRemoteGitRepoFilePresenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns Kubernetes machine types matching the request filters.
     * List Kubernetes machine types
     */
    async listIntegrationKubeMachineTypesRaw(requestParameters: ListIntegrationKubeMachineTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationKubeMachineTypes().'
            );
        }

        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling listIntegrationKubeMachineTypes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/kube-machine-types`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns Kubernetes machine types matching the request filters.
     * List Kubernetes machine types
     */
    async listIntegrationKubeMachineTypes(requestParameters: ListIntegrationKubeMachineTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.listIntegrationKubeMachineTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns Kubernetes regions matching the request filters.
     * List Kubernetes regions
     */
    async listIntegrationKubeRegionsRaw(requestParameters: ListIntegrationKubeRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationKubeRegions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/kube-regions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns Kubernetes regions matching the request filters.
     * List Kubernetes regions
     */
    async listIntegrationKubeRegions(requestParameters: ListIntegrationKubeRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.listIntegrationKubeRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns Kubernetes versions matching the request filters.
     * List Kubernetes versions
     */
    async listIntegrationKubeVersionsRaw(requestParameters: ListIntegrationKubeVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KubeVersion>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationKubeVersions().'
            );
        }

        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling listIntegrationKubeVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/kube-versions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns Kubernetes versions matching the request filters.
     * List Kubernetes versions
     */
    async listIntegrationKubeVersions(requestParameters: ListIntegrationKubeVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KubeVersion>> {
        const response = await this.listIntegrationKubeVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns Kubernetes zones matching the request filters.
     * List Kubernetes zones
     */
    async listIntegrationKubeZonesRaw(requestParameters: ListIntegrationKubeZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationKubeZones().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/kube-zones`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns Kubernetes zones matching the request filters.
     * List Kubernetes zones
     */
    async listIntegrationKubeZones(requestParameters: ListIntegrationKubeZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.listIntegrationKubeZonesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns remote Git repository branches matching the request filters.
     * List remote Git repository branches
     */
    async listIntegrationRemoteGitRepoBranchesRaw(requestParameters: ListIntegrationRemoteGitRepoBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationRemoteGitRepoBranches().'
            );
        }

        if (requestParameters['remoteGitRepoId'] == null) {
            throw new runtime.RequiredError(
                'remoteGitRepoId',
                'Required parameter "remoteGitRepoId" was null or undefined when calling listIntegrationRemoteGitRepoBranches().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['remoteGitRepoId'] != null) {
            queryParameters['remoteGitRepoId'] = requestParameters['remoteGitRepoId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/remote-git-repo-branches`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns remote Git repository branches matching the request filters.
     * List remote Git repository branches
     */
    async listIntegrationRemoteGitRepoBranches(requestParameters: ListIntegrationRemoteGitRepoBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listIntegrationRemoteGitRepoBranchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns remote Git repository tags matching the request filters.
     * List remote Git repository tags
     */
    async listIntegrationRemoteGitRepoTagsRaw(requestParameters: ListIntegrationRemoteGitRepoTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationRemoteGitRepoTags().'
            );
        }

        if (requestParameters['remoteGitRepoId'] == null) {
            throw new runtime.RequiredError(
                'remoteGitRepoId',
                'Required parameter "remoteGitRepoId" was null or undefined when calling listIntegrationRemoteGitRepoTags().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['remoteGitRepoId'] != null) {
            queryParameters['remoteGitRepoId'] = requestParameters['remoteGitRepoId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/remote-git-repo-tags`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns remote Git repository tags matching the request filters.
     * List remote Git repository tags
     */
    async listIntegrationRemoteGitRepoTags(requestParameters: ListIntegrationRemoteGitRepoTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listIntegrationRemoteGitRepoTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns remote Git repositories matching the request filters.
     * List remote Git repositories
     */
    async listIntegrationRemoteGitReposRaw(requestParameters: ListIntegrationRemoteGitReposRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RemoteGitRepo>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationRemoteGitRepos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/remote-git-repos`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns remote Git repositories matching the request filters.
     * List remote Git repositories
     */
    async listIntegrationRemoteGitRepos(requestParameters: ListIntegrationRemoteGitReposRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RemoteGitRepo>> {
        const response = await this.listIntegrationRemoteGitReposRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns integration scopes matching the request filters.
     * List integration scopes
     */
    async listIntegrationScopesRaw(requestParameters: ListIntegrationScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IntegrationScope>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationScopes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/scopes`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns integration scopes matching the request filters.
     * List integration scopes
     */
    async listIntegrationScopes(requestParameters: ListIntegrationScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IntegrationScope>> {
        const response = await this.listIntegrationScopesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns storage buckets matching the request filters.
     * List storage buckets
     */
    async listIntegrationStorageBucketsRaw(requestParameters: ListIntegrationStorageBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationStorageBuckets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/storage-buckets`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns storage buckets matching the request filters.
     * List storage buckets
     */
    async listIntegrationStorageBuckets(requestParameters: ListIntegrationStorageBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listIntegrationStorageBucketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns storage classes matching the request filters.
     * List storage classes
     */
    async listIntegrationStorageClassesRaw(requestParameters: ListIntegrationStorageClassesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listIntegrationStorageClasses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/options/storage-classes`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns storage classes matching the request filters.
     * List storage classes
     */
    async listIntegrationStorageClasses(requestParameters: ListIntegrationStorageClassesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listIntegrationStorageClassesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns integrations matching the request filters.
     * List integrations
     */
    async listIntegrationsRaw(requestParameters: ListIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Integration>>> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        if (requestParameters['projectIds'] != null) {
            queryParameters['projectIds'] = requestParameters['projectIds'];
        }

        if (requestParameters['labels'] != null) {
            queryParameters['labels'] = requestParameters['labels'];
        }

        if (requestParameters['envId'] != null) {
            queryParameters['envId'] = requestParameters['envId'];
        }

        if (requestParameters['envType'] != null) {
            queryParameters['envType'] = requestParameters['envType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns integrations matching the request filters.
     * List integrations
     */
    async listIntegrations(requestParameters: ListIntegrationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Integration>> {
        const response = await this.listIntegrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reuses an accessible integration when provider, kinds, scope, environment scopes, and credential values match exactly; otherwise creates it.
     * Resolve or create integration
     */
    async resolveIntegrationRaw(requestParameters: ResolveIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolveIntegrationResult>> {
        if (requestParameters['newIntegrationInput'] == null) {
            throw new runtime.RequiredError(
                'newIntegrationInput',
                'Required parameter "newIntegrationInput" was null or undefined when calling resolveIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/actions/resolve`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['newIntegrationInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Reuses an accessible integration when provider, kinds, scope, environment scopes, and credential values match exactly; otherwise creates it.
     * Resolve or create integration
     */
    async resolveIntegration(requestParameters: ResolveIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolveIntegrationResult> {
        const response = await this.resolveIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns accessible integrations matching structured type, status, label, variable, project, and environment requirements.
     * Search integrations
     */
    async searchIntegrationsRaw(requestParameters: SearchIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Integration>>> {
        if (requestParameters['searchIntegrationsInput'] == null) {
            throw new runtime.RequiredError(
                'searchIntegrationsInput',
                'Required parameter "searchIntegrationsInput" was null or undefined when calling searchIntegrations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/actions/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchIntegrationsInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns accessible integrations matching structured type, status, label, variable, project, and environment requirements.
     * Search integrations
     */
    async searchIntegrations(requestParameters: SearchIntegrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Integration>> {
        const response = await this.searchIntegrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts the provider permission audit configured by the integration\'s provider revision.
     * Test integration permissions
     */
    async testIntegrationPermissionsRaw(requestParameters: TestIntegrationPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling testIntegrationPermissions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/actions/test-permissions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Starts the provider permission audit configured by the integration\'s provider revision.
     * Test integration permissions
     */
    async testIntegrationPermissions(requestParameters: TestIntegrationPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.testIntegrationPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the integration and returns the updated resource.
     * Update integration
     */
    async updateIntegrationRaw(requestParameters: UpdateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateIntegration().'
            );
        }

        if (requestParameters['updateIntegrationInput'] == null) {
            throw new runtime.RequiredError(
                'updateIntegrationInput',
                'Required parameter "updateIntegrationInput" was null or undefined when calling updateIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateIntegrationInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Updates the integration and returns the updated resource.
     * Update integration
     */
    async updateIntegration(requestParameters: UpdateIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.updateIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the associated environment and exact allowed environment scope. Scope reductions that conflict with existing references are rejected.
     * Update integration environment policy
     */
    async updateIntegrationEnvironmentPolicyRaw(requestParameters: UpdateIntegrationEnvironmentPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Integration>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateIntegrationEnvironmentPolicy().'
            );
        }

        if (requestParameters['integrationEnvironmentPolicyInput'] == null) {
            throw new runtime.RequiredError(
                'integrationEnvironmentPolicyInput',
                'Required parameter "integrationEnvironmentPolicyInput" was null or undefined when calling updateIntegrationEnvironmentPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/environment-policy/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['integrationEnvironmentPolicyInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Updates the associated environment and exact allowed environment scope. Scope reductions that conflict with existing references are rejected.
     * Update integration environment policy
     */
    async updateIntegrationEnvironmentPolicy(requestParameters: UpdateIntegrationEnvironmentPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Integration> {
        const response = await this.updateIntegrationEnvironmentPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upgrades an integration to its eligible provider revision and optionally drops fields removed by the target contract.
     * Upgrade integration provider revision
     */
    async upgradeIntegrationProviderRevisionRaw(requestParameters: UpgradeIntegrationProviderRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling upgradeIntegrationProviderRevision().'
            );
        }

        if (requestParameters['upgradeIntegrationProviderRevisionInput'] == null) {
            throw new runtime.RequiredError(
                'upgradeIntegrationProviderRevisionInput',
                'Required parameter "upgradeIntegrationProviderRevisionInput" was null or undefined when calling upgradeIntegrationProviderRevision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/actions/upgrade-provider-revision`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['upgradeIntegrationProviderRevisionInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Upgrades an integration to its eligible provider revision and optionally drops fields removed by the target contract.
     * Upgrade integration provider revision
     */
    async upgradeIntegrationProviderRevision(requestParameters: UpgradeIntegrationProviderRevisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.upgradeIntegrationProviderRevisionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validates an app-access hostname against the provider settings of the integration.
     * Validate an app-access hostname
     */
    async validateAppAccessHostnameRaw(requestParameters: ValidateAppAccessHostnameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling validateAppAccessHostname().'
            );
        }

        if (requestParameters['validateAppAccessHostnameInput'] == null) {
            throw new runtime.RequiredError(
                'validateAppAccessHostnameInput',
                'Required parameter "validateAppAccessHostnameInput" was null or undefined when calling validateAppAccessHostname().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/integrations/{id}/actions/validate-app-access-hostname`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['validateAppAccessHostnameInput'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Validates an app-access hostname against the provider settings of the integration.
     * Validate an app-access hostname
     */
    async validateAppAccessHostname(requestParameters: ValidateAppAccessHostnameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidationResult> {
        const response = await this.validateAppAccessHostnameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListIntegrationsEnvTypeEnum = {
    Prod: 'prod',
    Test: 'test',
    Staging: 'staging',
    Dev: 'dev',
    Feature: 'feature'
} as const;
export type ListIntegrationsEnvTypeEnum = typeof ListIntegrationsEnvTypeEnum[keyof typeof ListIntegrationsEnvTypeEnum];
