/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Stack,
  StackRevision,
  StackService,
  StacksResponse,
} from '../models/index';
import {
    StackFromJSON,
    StackToJSON,
    StackRevisionFromJSON,
    StackRevisionToJSON,
    StackServiceFromJSON,
    StackServiceToJSON,
    StacksResponseFromJSON,
    StacksResponseToJSON,
} from '../models/index';

export interface StackRevisionsIdGetRequest {
    id: number;
}

export interface StackRevisionsIdServicesGetRequest {
    id: number;
}

export interface StacksByNameNameGetRequest {
    name: string;
    revNumber?: number;
}

export interface StacksGetRequest {
    orgId: number;
    projectIds?: string;
    search?: string;
    page?: number;
    pageSize?: number;
}

/**
 * StacksApi - interface
 * 
 * @export
 * @interface StacksApiInterface
 */
export interface StacksApiInterface {
    /**
     * 
     * @summary Get stack revision
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StacksApiInterface
     */
    stackRevisionsIdGetRaw(requestParameters: StackRevisionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StackRevision>>;

    /**
     * Get stack revision
     */
    stackRevisionsIdGet(requestParameters: StackRevisionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StackRevision>;

    /**
     * 
     * @summary List stack services
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StacksApiInterface
     */
    stackRevisionsIdServicesGetRaw(requestParameters: StackRevisionsIdServicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StackService>>>;

    /**
     * List stack services
     */
    stackRevisionsIdServicesGet(requestParameters: StackRevisionsIdServicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StackService>>;

    /**
     * 
     * @summary Get stack by name
     * @param {string} name 
     * @param {number} [revNumber] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StacksApiInterface
     */
    stacksByNameNameGetRaw(requestParameters: StacksByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stack>>;

    /**
     * Get stack by name
     */
    stacksByNameNameGet(requestParameters: StacksByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stack>;

    /**
     * 
     * @summary List stacks
     * @param {number} orgId 
     * @param {string} [projectIds] Comma-separated project ids
     * @param {string} [search] 
     * @param {number} [page] Page number, defaults to 1
     * @param {number} [pageSize] Page size, defaults to 30
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StacksApiInterface
     */
    stacksGetRaw(requestParameters: StacksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StacksResponse>>;

    /**
     * List stacks
     */
    stacksGet(requestParameters: StacksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StacksResponse>;

}

/**
 * 
 */
export class StacksApi extends runtime.BaseAPI implements StacksApiInterface {

    /**
     * Get stack revision
     */
    async stackRevisionsIdGetRaw(requestParameters: StackRevisionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StackRevision>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stackRevisionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/stack-revisions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StackRevisionFromJSON(jsonValue));
    }

    /**
     * Get stack revision
     */
    async stackRevisionsIdGet(requestParameters: StackRevisionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StackRevision> {
        const response = await this.stackRevisionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List stack services
     */
    async stackRevisionsIdServicesGetRaw(requestParameters: StackRevisionsIdServicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StackService>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stackRevisionsIdServicesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/stack-revisions/{id}/services`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StackServiceFromJSON));
    }

    /**
     * List stack services
     */
    async stackRevisionsIdServicesGet(requestParameters: StackRevisionsIdServicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StackService>> {
        const response = await this.stackRevisionsIdServicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get stack by name
     */
    async stacksByNameNameGetRaw(requestParameters: StacksByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stack>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling stacksByNameNameGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['revNumber'] != null) {
            queryParameters['revNumber'] = requestParameters['revNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/stacks/by-name/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StackFromJSON(jsonValue));
    }

    /**
     * Get stack by name
     */
    async stacksByNameNameGet(requestParameters: StacksByNameNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stack> {
        const response = await this.stacksByNameNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List stacks
     */
    async stacksGetRaw(requestParameters: StacksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StacksResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling stacksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        if (requestParameters['projectIds'] != null) {
            queryParameters['projectIds'] = requestParameters['projectIds'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/stacks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StacksResponseFromJSON(jsonValue));
    }

    /**
     * List stacks
     */
    async stacksGet(requestParameters: StacksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StacksResponse> {
        const response = await this.stacksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
