/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TaskStepLogs,
  URLResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TaskStepLogsFromJSON,
    TaskStepLogsToJSON,
    URLResponseFromJSON,
    URLResponseToJSON,
} from '../models/index';

export interface GetTaskStepLogUrlRequest {
    id: number;
}

export interface GetTaskStepLogsRequest {
    id: number;
    delivery?: GetTaskStepLogsDeliveryEnum;
}

/**
 * TaskStepsApi - interface
 * 
 * @export
 * @interface TaskStepsApiInterface
 */
export interface TaskStepsApiInterface {
    /**
     * Returns a temporary log URL for the task step.
     * @summary Get task step log URL
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskStepsApiInterface
     */
    getTaskStepLogUrlRaw(requestParameters: GetTaskStepLogUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<URLResponse>>;

    /**
     * Returns a temporary log URL for the task step.
     * Get task step log URL
     */
    getTaskStepLogUrl(requestParameters: GetTaskStepLogUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<URLResponse>;

    /**
     * Returns current inline logs for pending task steps and a temporary log URL for persisted task steps.
     * @summary Get task step logs
     * @param {number} id 
     * @param {'auto' | 'inline' | 'url'} [delivery] Delivery mode. Auto returns a URL for persisted logs and inline lines for pending or empty logs.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskStepsApiInterface
     */
    getTaskStepLogsRaw(requestParameters: GetTaskStepLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskStepLogs>>;

    /**
     * Returns current inline logs for pending task steps and a temporary log URL for persisted task steps.
     * Get task step logs
     */
    getTaskStepLogs(requestParameters: GetTaskStepLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskStepLogs>;

}

/**
 * 
 */
export class TaskStepsApi extends runtime.BaseAPI implements TaskStepsApiInterface {

    /**
     * Returns a temporary log URL for the task step.
     * Get task step log URL
     */
    async getTaskStepLogUrlRaw(requestParameters: GetTaskStepLogUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<URLResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTaskStepLogUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/task-steps/{id}/log-url`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => URLResponseFromJSON(jsonValue));
    }

    /**
     * Returns a temporary log URL for the task step.
     * Get task step log URL
     */
    async getTaskStepLogUrl(requestParameters: GetTaskStepLogUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<URLResponse> {
        const response = await this.getTaskStepLogUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns current inline logs for pending task steps and a temporary log URL for persisted task steps.
     * Get task step logs
     */
    async getTaskStepLogsRaw(requestParameters: GetTaskStepLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskStepLogs>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTaskStepLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delivery'] != null) {
            queryParameters['delivery'] = requestParameters['delivery'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/task-steps/{id}/logs`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskStepLogsFromJSON(jsonValue));
    }

    /**
     * Returns current inline logs for pending task steps and a temporary log URL for persisted task steps.
     * Get task step logs
     */
    async getTaskStepLogs(requestParameters: GetTaskStepLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskStepLogs> {
        const response = await this.getTaskStepLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTaskStepLogsDeliveryEnum = {
    Auto: 'auto',
    Inline: 'inline',
    Url: 'url'
} as const;
export type GetTaskStepLogsDeliveryEnum = typeof GetTaskStepLogsDeliveryEnum[keyof typeof GetTaskStepLogsDeliveryEnum];
