/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TaskStepLogs,
  URLResponse,
} from '../models/index';
import {
    TaskStepLogsFromJSON,
    TaskStepLogsToJSON,
    URLResponseFromJSON,
    URLResponseToJSON,
} from '../models/index';

export interface TaskStepsIdLogUrlGetRequest {
    id: number;
}

export interface TaskStepsIdLogsGetRequest {
    id: number;
}

/**
 * TaskStepsApi - interface
 * 
 * @export
 * @interface TaskStepsApiInterface
 */
export interface TaskStepsApiInterface {
    /**
     * 
     * @summary Get task step log URL
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskStepsApiInterface
     */
    taskStepsIdLogUrlGetRaw(requestParameters: TaskStepsIdLogUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<URLResponse>>;

    /**
     * Get task step log URL
     */
    taskStepsIdLogUrlGet(requestParameters: TaskStepsIdLogUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<URLResponse>;

    /**
     * 
     * @summary Get task step logs
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskStepsApiInterface
     */
    taskStepsIdLogsGetRaw(requestParameters: TaskStepsIdLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskStepLogs>>;

    /**
     * Get task step logs
     */
    taskStepsIdLogsGet(requestParameters: TaskStepsIdLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskStepLogs>;

}

/**
 * 
 */
export class TaskStepsApi extends runtime.BaseAPI implements TaskStepsApiInterface {

    /**
     * Get task step log URL
     */
    async taskStepsIdLogUrlGetRaw(requestParameters: TaskStepsIdLogUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<URLResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskStepsIdLogUrlGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/task-steps/{id}/log-url`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => URLResponseFromJSON(jsonValue));
    }

    /**
     * Get task step log URL
     */
    async taskStepsIdLogUrlGet(requestParameters: TaskStepsIdLogUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<URLResponse> {
        const response = await this.taskStepsIdLogUrlGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get task step logs
     */
    async taskStepsIdLogsGetRaw(requestParameters: TaskStepsIdLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskStepLogs>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskStepsIdLogsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-ACCESS-TOKEN"] = await this.configuration.apiKey("X-ACCESS-TOKEN"); // accessTokenHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apiKeyHeader authentication
        }

        const response = await this.request({
            path: `/task-steps/{id}/logs`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskStepLogsFromJSON(jsonValue));
    }

    /**
     * Get task step logs
     */
    async taskStepsIdLogsGet(requestParameters: TaskStepsIdLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskStepLogs> {
        const response = await this.taskStepsIdLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
