/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppBuild
 */
export interface AppBuild {
    /**
     * 
     * @type {number}
     * @memberof AppBuild
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AppBuild
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof AppBuild
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof AppBuild
     */
    appInstanceId: number;
    /**
     * 
     * @type {number}
     * @memberof AppBuild
     */
    appServiceId: number;
    /**
     * 
     * @type {string}
     * @memberof AppBuild
     */
    gitRefType: string;
    /**
     * 
     * @type {string}
     * @memberof AppBuild
     */
    gitRef: string;
    /**
     * 
     * @type {string}
     * @memberof AppBuild
     */
    commitHash: string;
    /**
     * 
     * @type {string}
     * @memberof AppBuild
     */
    commitMessage: string;
    /**
     * 
     * @type {Date}
     * @memberof AppBuild
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppBuild
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppBuild
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AppBuild
     */
    endedAt?: Date | null;
}

/**
 * Check if a given object implements the AppBuild interface.
 */
export function instanceOfAppBuild(value: object): value is AppBuild {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('appInstanceId' in value) || value['appInstanceId'] === undefined) return false;
    if (!('appServiceId' in value) || value['appServiceId'] === undefined) return false;
    if (!('gitRefType' in value) || value['gitRefType'] === undefined) return false;
    if (!('gitRef' in value) || value['gitRef'] === undefined) return false;
    if (!('commitHash' in value) || value['commitHash'] === undefined) return false;
    if (!('commitMessage' in value) || value['commitMessage'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AppBuildFromJSON(json: any): AppBuild {
    return AppBuildFromJSONTyped(json, false);
}

export function AppBuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppBuild {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'number': json['number'],
        'status': json['status'],
        'appInstanceId': json['appInstanceId'],
        'appServiceId': json['appServiceId'],
        'gitRefType': json['gitRefType'],
        'gitRef': json['gitRef'],
        'commitHash': json['commitHash'],
        'commitMessage': json['commitMessage'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
    };
}

export function AppBuildToJSON(json: any): AppBuild {
    return AppBuildToJSONTyped(json, false);
}

export function AppBuildToJSONTyped(value?: AppBuild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'status': value['status'],
        'appInstanceId': value['appInstanceId'],
        'appServiceId': value['appServiceId'],
        'gitRefType': value['gitRefType'],
        'gitRef': value['gitRef'],
        'commitHash': value['commitHash'],
        'commitMessage': value['commitMessage'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt'] as any).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt'] as any).toISOString()),
    };
}

