/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppBuild } from './AppBuild';
import {
    AppBuildFromJSON,
    AppBuildFromJSONTyped,
    AppBuildToJSON,
    AppBuildToJSONTyped,
} from './AppBuild';

/**
 * 
 * @export
 * @interface AppBuildsCreateResponse
 */
export interface AppBuildsCreateResponse {
    /**
     * 
     * @type {Array<AppBuild>}
     * @memberof AppBuildsCreateResponse
     */
    items: Array<AppBuild>;
    /**
     * 
     * @type {number}
     * @memberof AppBuildsCreateResponse
     */
    taskId?: number | null;
}

/**
 * Check if a given object implements the AppBuildsCreateResponse interface.
 */
export function instanceOfAppBuildsCreateResponse(value: object): value is AppBuildsCreateResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AppBuildsCreateResponseFromJSON(json: any): AppBuildsCreateResponse {
    return AppBuildsCreateResponseFromJSONTyped(json, false);
}

export function AppBuildsCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppBuildsCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AppBuildFromJSON)),
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function AppBuildsCreateResponseToJSON(json: any): AppBuildsCreateResponse {
    return AppBuildsCreateResponseToJSONTyped(json, false);
}

export function AppBuildsCreateResponseToJSONTyped(value?: AppBuildsCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AppBuildToJSON)),
        'taskId': value['taskId'],
    };
}

