/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppPort
 */
export interface AppPort {
    /**
     * 
     * @type {number}
     * @memberof AppPort
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AppPort
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppPort
     */
    protocol: string;
    /**
     * 
     * @type {number}
     * @memberof AppPort
     */
    number: number;
    /**
     * 
     * @type {number}
     * @memberof AppPort
     */
    publicPort?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AppPort
     */
    _private: boolean;
    /**
     * 
     * @type {number}
     * @memberof AppPort
     */
    appEndpointId: number;
    /**
     * 
     * @type {number}
     * @memberof AppPort
     */
    appInstanceId: number;
    /**
     * 
     * @type {number}
     * @memberof AppPort
     */
    appServiceId: number;
    /**
     * 
     * @type {Date}
     * @memberof AppPort
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppPort
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AppPort interface.
 */
export function instanceOfAppPort(value: object): value is AppPort {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('_private' in value) || value['_private'] === undefined) return false;
    if (!('appEndpointId' in value) || value['appEndpointId'] === undefined) return false;
    if (!('appInstanceId' in value) || value['appInstanceId'] === undefined) return false;
    if (!('appServiceId' in value) || value['appServiceId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AppPortFromJSON(json: any): AppPort {
    return AppPortFromJSONTyped(json, false);
}

export function AppPortFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPort {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'protocol': json['protocol'],
        'number': json['number'],
        'publicPort': json['publicPort'] == null ? undefined : json['publicPort'],
        '_private': json['private'],
        'appEndpointId': json['appEndpointId'],
        'appInstanceId': json['appInstanceId'],
        'appServiceId': json['appServiceId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function AppPortToJSON(json: any): AppPort {
    return AppPortToJSONTyped(json, false);
}

export function AppPortToJSONTyped(value?: AppPort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'protocol': value['protocol'],
        'number': value['number'],
        'publicPort': value['publicPort'],
        'private': value['_private'],
        'appEndpointId': value['appEndpointId'],
        'appInstanceId': value['appInstanceId'],
        'appServiceId': value['appServiceId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

