/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppServiceBuildArg } from './AppServiceBuildArg';
import {
    AppServiceBuildArgFromJSON,
    AppServiceBuildArgFromJSONTyped,
    AppServiceBuildArgToJSON,
    AppServiceBuildArgToJSONTyped,
} from './AppServiceBuildArg';

/**
 * 
 * @export
 * @interface AppServiceBuildConfig
 */
export interface AppServiceBuildConfig {
    /**
     * 
     * @type {string}
     * @memberof AppServiceBuildConfig
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppServiceBuildConfig
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceBuildConfig
     */
    managed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceBuildConfig
     */
    main: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppServiceBuildConfig
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof AppServiceBuildConfig
     */
    dockerfile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppServiceBuildConfig
     */
    dockerignore?: string | null;
    /**
     * 
     * @type {Array<AppServiceBuildArg>}
     * @memberof AppServiceBuildConfig
     */
    args?: Array<AppServiceBuildArg> | null;
}

/**
 * Check if a given object implements the AppServiceBuildConfig interface.
 */
export function instanceOfAppServiceBuildConfig(value: object): value is AppServiceBuildConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('managed' in value) || value['managed'] === undefined) return false;
    if (!('main' in value) || value['main'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function AppServiceBuildConfigFromJSON(json: any): AppServiceBuildConfig {
    return AppServiceBuildConfigFromJSONTyped(json, false);
}

export function AppServiceBuildConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceBuildConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'title': json['title'],
        'managed': json['managed'],
        'main': json['main'],
        'image': json['image'],
        'dockerfile': json['dockerfile'] == null ? undefined : json['dockerfile'],
        'dockerignore': json['dockerignore'] == null ? undefined : json['dockerignore'],
        'args': json['args'] == null ? undefined : ((json['args'] as Array<any>).map(AppServiceBuildArgFromJSON)),
    };
}

export function AppServiceBuildConfigToJSON(json: any): AppServiceBuildConfig {
    return AppServiceBuildConfigToJSONTyped(json, false);
}

export function AppServiceBuildConfigToJSONTyped(value?: AppServiceBuildConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'title': value['title'],
        'managed': value['managed'],
        'main': value['main'],
        'image': value['image'],
        'dockerfile': value['dockerfile'],
        'dockerignore': value['dockerignore'],
        'args': value['args'] == null ? undefined : ((value['args'] as Array<any>).map(AppServiceBuildArgToJSON)),
    };
}

