/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppServiceEnvVarSource
 */
export interface AppServiceEnvVarSource {
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceEnvVarSource
     */
    fromService: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceEnvVarSource
     */
    fromStack: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceEnvVarSource
     */
    fromWodby: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppServiceEnvVarSource
     */
    setting?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppServiceEnvVarSource
     */
    link?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppServiceEnvVarSource
     */
    integration?: string | null;
}

/**
 * Check if a given object implements the AppServiceEnvVarSource interface.
 */
export function instanceOfAppServiceEnvVarSource(value: object): value is AppServiceEnvVarSource {
    if (!('fromService' in value) || value['fromService'] === undefined) return false;
    if (!('fromStack' in value) || value['fromStack'] === undefined) return false;
    if (!('fromWodby' in value) || value['fromWodby'] === undefined) return false;
    return true;
}

export function AppServiceEnvVarSourceFromJSON(json: any): AppServiceEnvVarSource {
    return AppServiceEnvVarSourceFromJSONTyped(json, false);
}

export function AppServiceEnvVarSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceEnvVarSource {
    if (json == null) {
        return json;
    }
    return {
        
        'fromService': json['fromService'],
        'fromStack': json['fromStack'],
        'fromWodby': json['fromWodby'],
        'setting': json['setting'] == null ? undefined : json['setting'],
        'link': json['link'] == null ? undefined : json['link'],
        'integration': json['integration'] == null ? undefined : json['integration'],
    };
}

export function AppServiceEnvVarSourceToJSON(json: any): AppServiceEnvVarSource {
    return AppServiceEnvVarSourceToJSONTyped(json, false);
}

export function AppServiceEnvVarSourceToJSONTyped(value?: AppServiceEnvVarSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromService': value['fromService'],
        'fromStack': value['fromStack'],
        'fromWodby': value['fromWodby'],
        'setting': value['setting'],
        'link': value['link'],
        'integration': value['integration'],
    };
}

