/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppServiceConfig
 */
export interface AppServiceConfig {
    /**
     * 
     * @type {number}
     * @memberof AppServiceConfig
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AppServiceConfig
     */
    appServiceId: number;
    /**
     * 
     * @type {string}
     * @memberof AppServiceConfig
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppServiceConfig
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AppServiceConfig
     */
    config?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceConfig
     */
    disabled: boolean;
}

/**
 * Check if a given object implements the AppServiceConfig interface.
 */
export function instanceOfAppServiceConfig(value: object): value is AppServiceConfig {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appServiceId' in value) || value['appServiceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    return true;
}

export function AppServiceConfigFromJSON(json: any): AppServiceConfig {
    return AppServiceConfigFromJSONTyped(json, false);
}

export function AppServiceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appServiceId': json['appServiceId'],
        'name': json['name'],
        'title': json['title'],
        'config': json['config'] == null ? undefined : json['config'],
        'disabled': json['disabled'],
    };
}

export function AppServiceConfigToJSON(json: any): AppServiceConfig {
    return AppServiceConfigToJSONTyped(json, false);
}

export function AppServiceConfigToJSONTyped(value?: AppServiceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'appServiceId': value['appServiceId'],
        'name': value['name'],
        'title': value['title'],
        'config': value['config'],
        'disabled': value['disabled'],
    };
}

