/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppServiceSettingInput
 */
export interface AppServiceSettingInput {
    /**
     * 
     * @type {string}
     * @memberof AppServiceSettingInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppServiceSettingInput
     */
    value: string;
}

/**
 * Check if a given object implements the AppServiceSettingInput interface.
 */
export function instanceOfAppServiceSettingInput(value: object): value is AppServiceSettingInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AppServiceSettingInputFromJSON(json: any): AppServiceSettingInput {
    return AppServiceSettingInputFromJSONTyped(json, false);
}

export function AppServiceSettingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceSettingInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function AppServiceSettingInputToJSON(json: any): AppServiceSettingInput {
    return AppServiceSettingInputToJSONTyped(json, false);
}

export function AppServiceSettingInputToJSONTyped(value?: AppServiceSettingInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

