/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppServiceContainer
 */
export interface AppServiceContainer {
    /**
     * 
     * @type {number}
     * @memberof AppServiceContainer
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppServiceContainer
     */
    appServiceId: number;
    /**
     * 
     * @type {string}
     * @memberof AppServiceContainer
     */
    workload: string;
    /**
     * 
     * @type {string}
     * @memberof AppServiceContainer
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AppServiceContainer
     */
    requestCPU?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppServiceContainer
     */
    requestMem?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppServiceContainer
     */
    limitCPU?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppServiceContainer
     */
    limitMem?: number | null;
}

/**
 * Check if a given object implements the AppServiceContainer interface.
 */
export function instanceOfAppServiceContainer(value: object): value is AppServiceContainer {
    if (!('appServiceId' in value) || value['appServiceId'] === undefined) return false;
    if (!('workload' in value) || value['workload'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AppServiceContainerFromJSON(json: any): AppServiceContainer {
    return AppServiceContainerFromJSONTyped(json, false);
}

export function AppServiceContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceContainer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appServiceId': json['appServiceId'],
        'workload': json['workload'],
        'name': json['name'],
        'requestCPU': json['requestCPU'] == null ? undefined : json['requestCPU'],
        'requestMem': json['requestMem'] == null ? undefined : json['requestMem'],
        'limitCPU': json['limitCPU'] == null ? undefined : json['limitCPU'],
        'limitMem': json['limitMem'] == null ? undefined : json['limitMem'],
    };
}

export function AppServiceContainerToJSON(json: any): AppServiceContainer {
    return AppServiceContainerToJSONTyped(json, false);
}

export function AppServiceContainerToJSONTyped(value?: AppServiceContainer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'appServiceId': value['appServiceId'],
        'workload': value['workload'],
        'name': value['name'],
        'requestCPU': value['requestCPU'],
        'requestMem': value['requestMem'],
        'limitCPU': value['limitCPU'],
        'limitMem': value['limitMem'],
    };
}

