/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppServiceAnnotationSource
 */
export interface AppServiceAnnotationSource {
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceAnnotationSource
     */
    fromService: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceAnnotationSource
     */
    fromStack: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppServiceAnnotationSource
     */
    fromWodby: boolean;
}

/**
 * Check if a given object implements the AppServiceAnnotationSource interface.
 */
export function instanceOfAppServiceAnnotationSource(value: object): value is AppServiceAnnotationSource {
    if (!('fromService' in value) || value['fromService'] === undefined) return false;
    if (!('fromStack' in value) || value['fromStack'] === undefined) return false;
    if (!('fromWodby' in value) || value['fromWodby'] === undefined) return false;
    return true;
}

export function AppServiceAnnotationSourceFromJSON(json: any): AppServiceAnnotationSource {
    return AppServiceAnnotationSourceFromJSONTyped(json, false);
}

export function AppServiceAnnotationSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceAnnotationSource {
    if (json == null) {
        return json;
    }
    return {
        
        'fromService': json['fromService'],
        'fromStack': json['fromStack'],
        'fromWodby': json['fromWodby'],
    };
}

export function AppServiceAnnotationSourceToJSON(json: any): AppServiceAnnotationSource {
    return AppServiceAnnotationSourceToJSONTyped(json, false);
}

export function AppServiceAnnotationSourceToJSONTyped(value?: AppServiceAnnotationSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromService': value['fromService'],
        'fromStack': value['fromStack'],
        'fromWodby': value['fromWodby'],
    };
}

