/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppServiceDatabaseInput
 */
export interface AppServiceDatabaseInput {
    /**
     * 
     * @type {number}
     * @memberof AppServiceDatabaseInput
     */
    databaseID: number;
    /**
     * 
     * @type {number}
     * @memberof AppServiceDatabaseInput
     */
    databaseDBID?: number | null;
}

/**
 * Check if a given object implements the AppServiceDatabaseInput interface.
 */
export function instanceOfAppServiceDatabaseInput(value: object): value is AppServiceDatabaseInput {
    if (!('databaseID' in value) || value['databaseID'] === undefined) return false;
    return true;
}

export function AppServiceDatabaseInputFromJSON(json: any): AppServiceDatabaseInput {
    return AppServiceDatabaseInputFromJSONTyped(json, false);
}

export function AppServiceDatabaseInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppServiceDatabaseInput {
    if (json == null) {
        return json;
    }
    return {
        
        'databaseID': json['databaseID'],
        'databaseDBID': json['databaseDBID'] == null ? undefined : json['databaseDBID'],
    };
}

export function AppServiceDatabaseInputToJSON(json: any): AppServiceDatabaseInput {
    return AppServiceDatabaseInputToJSONTyped(json, false);
}

export function AppServiceDatabaseInputToJSONTyped(value?: AppServiceDatabaseInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'databaseID': value['databaseID'],
        'databaseDBID': value['databaseDBID'],
    };
}

