/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterAutoUpgradeVersionPolicyInput
 */
export interface ClusterAutoUpgradeVersionPolicyInput {
    /**
     * 
     * @type {boolean}
     * @memberof ClusterAutoUpgradeVersionPolicyInput
     */
    allowPatch?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ClusterAutoUpgradeVersionPolicyInput
     */
    allowMinor?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ClusterAutoUpgradeVersionPolicyInput
     */
    allowMajor?: boolean | null;
}

/**
 * Check if a given object implements the ClusterAutoUpgradeVersionPolicyInput interface.
 */
export function instanceOfClusterAutoUpgradeVersionPolicyInput(value: object): value is ClusterAutoUpgradeVersionPolicyInput {
    return true;
}

export function ClusterAutoUpgradeVersionPolicyInputFromJSON(json: any): ClusterAutoUpgradeVersionPolicyInput {
    return ClusterAutoUpgradeVersionPolicyInputFromJSONTyped(json, false);
}

export function ClusterAutoUpgradeVersionPolicyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterAutoUpgradeVersionPolicyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'allowPatch': json['allowPatch'] == null ? undefined : json['allowPatch'],
        'allowMinor': json['allowMinor'] == null ? undefined : json['allowMinor'],
        'allowMajor': json['allowMajor'] == null ? undefined : json['allowMajor'],
    };
}

export function ClusterAutoUpgradeVersionPolicyInputToJSON(json: any): ClusterAutoUpgradeVersionPolicyInput {
    return ClusterAutoUpgradeVersionPolicyInputToJSONTyped(json, false);
}

export function ClusterAutoUpgradeVersionPolicyInputToJSONTyped(value?: ClusterAutoUpgradeVersionPolicyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowPatch': value['allowPatch'],
        'allowMinor': value['allowMinor'],
        'allowMajor': value['allowMajor'],
    };
}

