/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigOverrideInput
 */
export interface ConfigOverrideInput {
    /**
     * 
     * @type {string}
     * @memberof ConfigOverrideInput
     */
    config?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigOverrideInput
     */
    disabled?: boolean | null;
}

/**
 * Check if a given object implements the ConfigOverrideInput interface.
 */
export function instanceOfConfigOverrideInput(value: object): value is ConfigOverrideInput {
    return true;
}

export function ConfigOverrideInputFromJSON(json: any): ConfigOverrideInput {
    return ConfigOverrideInputFromJSONTyped(json, false);
}

export function ConfigOverrideInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigOverrideInput {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
    };
}

export function ConfigOverrideInputToJSON(json: any): ConfigOverrideInput {
    return ConfigOverrideInputToJSONTyped(json, false);
}

export function ConfigOverrideInputToJSONTyped(value?: ConfigOverrideInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'disabled': value['disabled'],
    };
}

