/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrgRequest
 */
export interface CreateOrgRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrgRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrgRequest
     */
    title: string;
}

/**
 * Check if a given object implements the CreateOrgRequest interface.
 */
export function instanceOfCreateOrgRequest(value: object): value is CreateOrgRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateOrgRequestFromJSON(json: any): CreateOrgRequest {
    return CreateOrgRequestFromJSONTyped(json, false);
}

export function CreateOrgRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrgRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'title': json['title'],
    };
}

export function CreateOrgRequestToJSON(json: any): CreateOrgRequest {
    return CreateOrgRequestToJSONTyped(json, false);
}

export function CreateOrgRequestToJSONTyped(value?: CreateOrgRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'title': value['title'],
    };
}

