/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatabaseVersion
 */
export interface DatabaseVersion {
    /**
     * 
     * @type {string}
     * @memberof DatabaseVersion
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseVersion
     */
    title: string;
}

/**
 * Check if a given object implements the DatabaseVersion interface.
 */
export function instanceOfDatabaseVersion(value: object): value is DatabaseVersion {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DatabaseVersionFromJSON(json: any): DatabaseVersion {
    return DatabaseVersionFromJSONTyped(json, false);
}

export function DatabaseVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'title': json['title'],
    };
}

export function DatabaseVersionToJSON(json: any): DatabaseVersion {
    return DatabaseVersionToJSONTyped(json, false);
}

export function DatabaseVersionToJSONTyped(value?: DatabaseVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'title': value['title'],
    };
}

