/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Database
 */
export interface Database {
    /**
     * 
     * @type {number}
     * @memberof Database
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    region?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Database
     */
    zone?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Database
     */
    integrationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Database
     */
    envId: number;
    /**
     * 
     * @type {number}
     * @memberof Database
     */
    orgId: number;
    /**
     * 
     * @type {Date}
     * @memberof Database
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Database
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Database interface.
 */
export function instanceOfDatabase(value: object): value is Database {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('envId' in value) || value['envId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DatabaseFromJSON(json: any): Database {
    return DatabaseFromJSONTyped(json, false);
}

export function DatabaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Database {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'type': json['type'],
        'kind': json['kind'],
        'status': json['status'],
        'version': json['version'],
        'region': json['region'] == null ? undefined : json['region'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'integrationId': json['integrationId'] == null ? undefined : json['integrationId'],
        'envId': json['envId'],
        'orgId': json['orgId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function DatabaseToJSON(json: any): Database {
    return DatabaseToJSONTyped(json, false);
}

export function DatabaseToJSONTyped(value?: Database | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'type': value['type'],
        'kind': value['kind'],
        'status': value['status'],
        'version': value['version'],
        'region': value['region'],
        'zone': value['zone'],
        'integrationId': value['integrationId'],
        'envId': value['envId'],
        'orgId': value['orgId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

