/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockerRegistryCredentials
 */
export interface DockerRegistryCredentials {
    /**
     * 
     * @type {string}
     * @memberof DockerRegistryCredentials
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof DockerRegistryCredentials
     */
    password: string;
}

/**
 * Check if a given object implements the DockerRegistryCredentials interface.
 */
export function instanceOfDockerRegistryCredentials(value: object): value is DockerRegistryCredentials {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function DockerRegistryCredentialsFromJSON(json: any): DockerRegistryCredentials {
    return DockerRegistryCredentialsFromJSONTyped(json, false);
}

export function DockerRegistryCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerRegistryCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function DockerRegistryCredentialsToJSON(json: any): DockerRegistryCredentials {
    return DockerRegistryCredentialsToJSONTyped(json, false);
}

export function DockerRegistryCredentialsToJSONTyped(value?: DockerRegistryCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

