/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitAutoUpdateSettingsInput
 */
export interface GitAutoUpdateSettingsInput {
    /**
     * 
     * @type {boolean}
     * @memberof GitAutoUpdateSettingsInput
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GitAutoUpdateSettingsInput
     */
    branches: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GitAutoUpdateSettingsInput
     */
    semverTags: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GitAutoUpdateSettingsInput
     */
    allowPatch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GitAutoUpdateSettingsInput
     */
    allowMinor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GitAutoUpdateSettingsInput
     */
    allowMajor: boolean;
}

/**
 * Check if a given object implements the GitAutoUpdateSettingsInput interface.
 */
export function instanceOfGitAutoUpdateSettingsInput(value: object): value is GitAutoUpdateSettingsInput {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('branches' in value) || value['branches'] === undefined) return false;
    if (!('semverTags' in value) || value['semverTags'] === undefined) return false;
    if (!('allowPatch' in value) || value['allowPatch'] === undefined) return false;
    if (!('allowMinor' in value) || value['allowMinor'] === undefined) return false;
    if (!('allowMajor' in value) || value['allowMajor'] === undefined) return false;
    return true;
}

export function GitAutoUpdateSettingsInputFromJSON(json: any): GitAutoUpdateSettingsInput {
    return GitAutoUpdateSettingsInputFromJSONTyped(json, false);
}

export function GitAutoUpdateSettingsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitAutoUpdateSettingsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'branches': json['branches'],
        'semverTags': json['semverTags'],
        'allowPatch': json['allowPatch'],
        'allowMinor': json['allowMinor'],
        'allowMajor': json['allowMajor'],
    };
}

export function GitAutoUpdateSettingsInputToJSON(json: any): GitAutoUpdateSettingsInput {
    return GitAutoUpdateSettingsInputToJSONTyped(json, false);
}

export function GitAutoUpdateSettingsInputToJSONTyped(value?: GitAutoUpdateSettingsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'branches': value['branches'],
        'semverTags': value['semverTags'],
        'allowPatch': value['allowPatch'],
        'allowMinor': value['allowMinor'],
        'allowMajor': value['allowMajor'],
    };
}

