/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewAppServiceLogStreamInput
 */
export interface NewAppServiceLogStreamInput {
    /**
     * 
     * @type {string}
     * @memberof NewAppServiceLogStreamInput
     */
    workload?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewAppServiceLogStreamInput
     */
    container?: string | null;
}

/**
 * Check if a given object implements the NewAppServiceLogStreamInput interface.
 */
export function instanceOfNewAppServiceLogStreamInput(value: object): value is NewAppServiceLogStreamInput {
    return true;
}

export function NewAppServiceLogStreamInputFromJSON(json: any): NewAppServiceLogStreamInput {
    return NewAppServiceLogStreamInputFromJSONTyped(json, false);
}

export function NewAppServiceLogStreamInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAppServiceLogStreamInput {
    if (json == null) {
        return json;
    }
    return {
        
        'workload': json['workload'] == null ? undefined : json['workload'],
        'container': json['container'] == null ? undefined : json['container'],
    };
}

export function NewAppServiceLogStreamInputToJSON(json: any): NewAppServiceLogStreamInput {
    return NewAppServiceLogStreamInputToJSONTyped(json, false);
}

export function NewAppServiceLogStreamInputToJSONTyped(value?: NewAppServiceLogStreamInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workload': value['workload'],
        'container': value['container'],
    };
}

