/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewManagedClusterInput } from './NewManagedClusterInput';
import {
    NewManagedClusterInputFromJSON,
    NewManagedClusterInputFromJSONTyped,
    NewManagedClusterInputToJSON,
    NewManagedClusterInputToJSONTyped,
} from './NewManagedClusterInput';
import type { NewAppServiceInput } from './NewAppServiceInput';
import {
    NewAppServiceInputFromJSON,
    NewAppServiceInputFromJSONTyped,
    NewAppServiceInputToJSON,
    NewAppServiceInputToJSONTyped,
} from './NewAppServiceInput';

/**
 * 
 * @export
 * @interface NewAppInput
 */
export interface NewAppInput {
    /**
     * Optional for API-key requests; defaults to the API key's organization.
     * @type {number}
     * @memberof NewAppInput
     */
    orgId?: number;
    /**
     * 
     * @type {string}
     * @memberof NewAppInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewAppInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewAppInput
     */
    instanceName: string;
    /**
     * 
     * @type {string}
     * @memberof NewAppInput
     */
    instanceTitle: string;
    /**
     * 
     * @type {string}
     * @memberof NewAppInput
     */
    domain: string;
    /**
     * 
     * @type {number}
     * @memberof NewAppInput
     */
    projectId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NewAppInput
     */
    stackRevId: number;
    /**
     * 
     * @type {Array<NewAppServiceInput>}
     * @memberof NewAppInput
     */
    services: Array<NewAppServiceInput>;
    /**
     * 
     * @type {number}
     * @memberof NewAppInput
     */
    clusterId?: number | null;
    /**
     * 
     * @type {NewManagedClusterInput}
     * @memberof NewAppInput
     */
    newCluster?: NewManagedClusterInput;
    /**
     * 
     * @type {number}
     * @memberof NewAppInput
     */
    envId: number;
    /**
     * 
     * @type {number}
     * @memberof NewAppInput
     */
    ciIntegrationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NewAppInput
     */
    registryIntegrationId?: number | null;
}

/**
 * Check if a given object implements the NewAppInput interface.
 */
export function instanceOfNewAppInput(value: object): value is NewAppInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('instanceName' in value) || value['instanceName'] === undefined) return false;
    if (!('instanceTitle' in value) || value['instanceTitle'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('stackRevId' in value) || value['stackRevId'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    if (!('envId' in value) || value['envId'] === undefined) return false;
    return true;
}

export function NewAppInputFromJSON(json: any): NewAppInput {
    return NewAppInputFromJSONTyped(json, false);
}

export function NewAppInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAppInput {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'name': json['name'],
        'title': json['title'],
        'instanceName': json['instanceName'],
        'instanceTitle': json['instanceTitle'],
        'domain': json['domain'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'stackRevId': json['stackRevId'],
        'services': ((json['services'] as Array<any>).map(NewAppServiceInputFromJSON)),
        'clusterId': json['clusterId'] == null ? undefined : json['clusterId'],
        'newCluster': json['newCluster'] == null ? undefined : NewManagedClusterInputFromJSON(json['newCluster']),
        'envId': json['envId'],
        'ciIntegrationId': json['ciIntegrationId'] == null ? undefined : json['ciIntegrationId'],
        'registryIntegrationId': json['registryIntegrationId'] == null ? undefined : json['registryIntegrationId'],
    };
}

export function NewAppInputToJSON(json: any): NewAppInput {
    return NewAppInputToJSONTyped(json, false);
}

export function NewAppInputToJSONTyped(value?: NewAppInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgId': value['orgId'],
        'name': value['name'],
        'title': value['title'],
        'instanceName': value['instanceName'],
        'instanceTitle': value['instanceTitle'],
        'domain': value['domain'],
        'projectId': value['projectId'],
        'stackRevId': value['stackRevId'],
        'services': ((value['services'] as Array<any>).map(NewAppServiceInputToJSON)),
        'clusterId': value['clusterId'],
        'newCluster': NewManagedClusterInputToJSON(value['newCluster']),
        'envId': value['envId'],
        'ciIntegrationId': value['ciIntegrationId'],
        'registryIntegrationId': value['registryIntegrationId'],
    };
}

