/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewBuildFromCIInput
 */
export interface NewBuildFromCIInput {
    /**
     * 
     * @type {number}
     * @memberof NewBuildFromCIInput
     */
    appServiceID: number;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    gitCommitSHA: string;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    gitRef: string;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    gitRefType: string;
    /**
     * 
     * @type {number}
     * @memberof NewBuildFromCIInput
     */
    buildNum: number;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    buildID: string;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    workflow?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    gitCommitAuthorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    gitCommitAuthorEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    gitCommitMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof NewBuildFromCIInput
     */
    postDeployment?: string | null;
}

/**
 * Check if a given object implements the NewBuildFromCIInput interface.
 */
export function instanceOfNewBuildFromCIInput(value: object): value is NewBuildFromCIInput {
    if (!('appServiceID' in value) || value['appServiceID'] === undefined) return false;
    if (!('gitCommitSHA' in value) || value['gitCommitSHA'] === undefined) return false;
    if (!('gitRef' in value) || value['gitRef'] === undefined) return false;
    if (!('gitRefType' in value) || value['gitRefType'] === undefined) return false;
    if (!('buildNum' in value) || value['buildNum'] === undefined) return false;
    if (!('buildID' in value) || value['buildID'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function NewBuildFromCIInputFromJSON(json: any): NewBuildFromCIInput {
    return NewBuildFromCIInputFromJSONTyped(json, false);
}

export function NewBuildFromCIInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewBuildFromCIInput {
    if (json == null) {
        return json;
    }
    return {
        
        'appServiceID': json['appServiceID'],
        'gitCommitSHA': json['gitCommitSHA'],
        'gitRef': json['gitRef'],
        'gitRefType': json['gitRefType'],
        'buildNum': json['buildNum'],
        'buildID': json['buildID'],
        'workflow': json['workflow'] == null ? undefined : json['workflow'],
        'gitCommitAuthorName': json['gitCommitAuthorName'] == null ? undefined : json['gitCommitAuthorName'],
        'gitCommitAuthorEmail': json['gitCommitAuthorEmail'] == null ? undefined : json['gitCommitAuthorEmail'],
        'gitCommitMessage': json['gitCommitMessage'] == null ? undefined : json['gitCommitMessage'],
        'provider': json['provider'],
        'postDeployment': json['postDeployment'] == null ? undefined : json['postDeployment'],
    };
}

export function NewBuildFromCIInputToJSON(json: any): NewBuildFromCIInput {
    return NewBuildFromCIInputToJSONTyped(json, false);
}

export function NewBuildFromCIInputToJSONTyped(value?: NewBuildFromCIInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appServiceID': value['appServiceID'],
        'gitCommitSHA': value['gitCommitSHA'],
        'gitRef': value['gitRef'],
        'gitRefType': value['gitRefType'],
        'buildNum': value['buildNum'],
        'buildID': value['buildID'],
        'workflow': value['workflow'],
        'gitCommitAuthorName': value['gitCommitAuthorName'],
        'gitCommitAuthorEmail': value['gitCommitAuthorEmail'],
        'gitCommitMessage': value['gitCommitMessage'],
        'provider': value['provider'],
        'postDeployment': value['postDeployment'],
    };
}

