/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewBackupInput
 */
export interface NewBackupInput {
    /**
     * 
     * @type {number}
     * @memberof NewBackupInput
     */
    appServiceID?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NewBackupInput
     */
    databaseDBID?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NewBackupInput
     */
    backupName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NewBackupInput
     */
    integrationID: number;
    /**
     * 
     * @type {string}
     * @memberof NewBackupInput
     */
    bucket: string;
    /**
     * 
     * @type {string}
     * @memberof NewBackupInput
     */
    storageClass?: string | null;
}

/**
 * Check if a given object implements the NewBackupInput interface.
 */
export function instanceOfNewBackupInput(value: object): value is NewBackupInput {
    if (!('integrationID' in value) || value['integrationID'] === undefined) return false;
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    return true;
}

export function NewBackupInputFromJSON(json: any): NewBackupInput {
    return NewBackupInputFromJSONTyped(json, false);
}

export function NewBackupInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewBackupInput {
    if (json == null) {
        return json;
    }
    return {
        
        'appServiceID': json['appServiceID'] == null ? undefined : json['appServiceID'],
        'databaseDBID': json['databaseDBID'] == null ? undefined : json['databaseDBID'],
        'backupName': json['backupName'] == null ? undefined : json['backupName'],
        'integrationID': json['integrationID'],
        'bucket': json['bucket'],
        'storageClass': json['storageClass'] == null ? undefined : json['storageClass'],
    };
}

export function NewBackupInputToJSON(json: any): NewBackupInput {
    return NewBackupInputToJSONTyped(json, false);
}

export function NewBackupInputToJSONTyped(value?: NewBackupInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appServiceID': value['appServiceID'],
        'databaseDBID': value['databaseDBID'],
        'backupName': value['backupName'],
        'integrationID': value['integrationID'],
        'bucket': value['bucket'],
        'storageClass': value['storageClass'],
    };
}

