/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewDatabaseUserInput
 */
export interface NewDatabaseUserInput {
    /**
     * 
     * @type {number}
     * @memberof NewDatabaseUserInput
     */
    databaseId: number;
    /**
     * 
     * @type {string}
     * @memberof NewDatabaseUserInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewDatabaseUserInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof NewDatabaseUserInput
     */
    hostname?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof NewDatabaseUserInput
     */
    databaseDbIds?: Array<number>;
}

/**
 * Check if a given object implements the NewDatabaseUserInput interface.
 */
export function instanceOfNewDatabaseUserInput(value: object): value is NewDatabaseUserInput {
    if (!('databaseId' in value) || value['databaseId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function NewDatabaseUserInputFromJSON(json: any): NewDatabaseUserInput {
    return NewDatabaseUserInputFromJSONTyped(json, false);
}

export function NewDatabaseUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewDatabaseUserInput {
    if (json == null) {
        return json;
    }
    return {
        
        'databaseId': json['databaseId'],
        'name': json['name'],
        'password': json['password'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'databaseDbIds': json['databaseDbIds'] == null ? undefined : json['databaseDbIds'],
    };
}

export function NewDatabaseUserInputToJSON(json: any): NewDatabaseUserInput {
    return NewDatabaseUserInputToJSONTyped(json, false);
}

export function NewDatabaseUserInputToJSONTyped(value?: NewDatabaseUserInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'databaseId': value['databaseId'],
        'name': value['name'],
        'password': value['password'],
        'hostname': value['hostname'],
        'databaseDbIds': value['databaseDbIds'],
    };
}

