/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldInput } from './FieldInput';
import {
    FieldInputFromJSON,
    FieldInputFromJSONTyped,
    FieldInputToJSON,
    FieldInputToJSONTyped,
} from './FieldInput';

/**
 * 
 * @export
 * @interface NewIntegrationInput
 */
export interface NewIntegrationInput {
    /**
     * 
     * @type {number}
     * @memberof NewIntegrationInput
     */
    orgID: number;
    /**
     * 
     * @type {number}
     * @memberof NewIntegrationInput
     */
    providerID: number;
    /**
     * 
     * @type {string}
     * @memberof NewIntegrationInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewIntegrationInput
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewIntegrationInput
     */
    kinds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewIntegrationInput
     */
    auth?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NewIntegrationInput
     */
    projectID?: number | null;
    /**
     * 
     * @type {Array<FieldInput>}
     * @memberof NewIntegrationInput
     */
    fieldsInput?: Array<FieldInput>;
    /**
     * 
     * @type {string}
     * @memberof NewIntegrationInput
     */
    scope?: string | null;
}

/**
 * Check if a given object implements the NewIntegrationInput interface.
 */
export function instanceOfNewIntegrationInput(value: object): value is NewIntegrationInput {
    if (!('orgID' in value) || value['orgID'] === undefined) return false;
    if (!('providerID' in value) || value['providerID'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('kinds' in value) || value['kinds'] === undefined) return false;
    return true;
}

export function NewIntegrationInputFromJSON(json: any): NewIntegrationInput {
    return NewIntegrationInputFromJSONTyped(json, false);
}

export function NewIntegrationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewIntegrationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'orgID': json['orgID'],
        'providerID': json['providerID'],
        'name': json['name'],
        'title': json['title'],
        'kinds': json['kinds'],
        'auth': json['auth'] == null ? undefined : json['auth'],
        'projectID': json['projectID'] == null ? undefined : json['projectID'],
        'fieldsInput': json['fieldsInput'] == null ? undefined : ((json['fieldsInput'] as Array<any>).map(FieldInputFromJSON)),
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function NewIntegrationInputToJSON(json: any): NewIntegrationInput {
    return NewIntegrationInputToJSONTyped(json, false);
}

export function NewIntegrationInputToJSONTyped(value?: NewIntegrationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgID': value['orgID'],
        'providerID': value['providerID'],
        'name': value['name'],
        'title': value['title'],
        'kinds': value['kinds'],
        'auth': value['auth'],
        'projectID': value['projectID'],
        'fieldsInput': value['fieldsInput'] == null ? undefined : ((value['fieldsInput'] as Array<any>).map(FieldInputToJSON)),
        'scope': value['scope'],
    };
}

