/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewStackServiceTokenInput
 */
export interface NewStackServiceTokenInput {
    /**
     * 
     * @type {string}
     * @memberof NewStackServiceTokenInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewStackServiceTokenInput
     */
    value?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof NewStackServiceTokenInput
     */
    secret: boolean;
    /**
     * 
     * @type {string}
     * @memberof NewStackServiceTokenInput
     */
    regex?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewStackServiceTokenInput
     */
    envType?: string | null;
}

/**
 * Check if a given object implements the NewStackServiceTokenInput interface.
 */
export function instanceOfNewStackServiceTokenInput(value: object): value is NewStackServiceTokenInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function NewStackServiceTokenInputFromJSON(json: any): NewStackServiceTokenInput {
    return NewStackServiceTokenInputFromJSONTyped(json, false);
}

export function NewStackServiceTokenInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewStackServiceTokenInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'secret': json['secret'],
        'regex': json['regex'] == null ? undefined : json['regex'],
        'envType': json['envType'] == null ? undefined : json['envType'],
    };
}

export function NewStackServiceTokenInputToJSON(json: any): NewStackServiceTokenInput {
    return NewStackServiceTokenInputToJSONTyped(json, false);
}

export function NewStackServiceTokenInputToJSONTyped(value?: NewStackServiceTokenInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'secret': value['secret'],
        'regex': value['regex'],
        'envType': value['envType'],
    };
}

