/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
    ProviderToJSONTyped,
} from './Provider';

/**
 * 
 * @export
 * @interface ProvidersResponse
 */
export interface ProvidersResponse {
    /**
     * 
     * @type {Array<Provider>}
     * @memberof ProvidersResponse
     */
    items: Array<Provider>;
    /**
     * 
     * @type {number}
     * @memberof ProvidersResponse
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProvidersResponse
     */
    nextPage?: number | null;
}

/**
 * Check if a given object implements the ProvidersResponse interface.
 */
export function instanceOfProvidersResponse(value: object): value is ProvidersResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function ProvidersResponseFromJSON(json: any): ProvidersResponse {
    return ProvidersResponseFromJSONTyped(json, false);
}

export function ProvidersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvidersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProviderFromJSON)),
        'totalCount': json['totalCount'],
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
    };
}

export function ProvidersResponseToJSON(json: any): ProvidersResponse {
    return ProvidersResponseToJSONTyped(json, false);
}

export function ProvidersResponseToJSONTyped(value?: ProvidersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProviderToJSON)),
        'totalCount': value['totalCount'],
        'nextPage': value['nextPage'],
    };
}

