/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteGitRepo
 */
export interface RemoteGitRepo {
    /**
     * 
     * @type {string}
     * @memberof RemoteGitRepo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteGitRepo
     */
    name: string;
}

/**
 * Check if a given object implements the RemoteGitRepo interface.
 */
export function instanceOfRemoteGitRepo(value: object): value is RemoteGitRepo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RemoteGitRepoFromJSON(json: any): RemoteGitRepo {
    return RemoteGitRepoFromJSONTyped(json, false);
}

export function RemoteGitRepoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteGitRepo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function RemoteGitRepoToJSON(json: any): RemoteGitRepo {
    return RemoteGitRepoToJSONTyped(json, false);
}

export function RemoteGitRepoToJSONTyped(value?: RemoteGitRepo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

