/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepeatTaskRequest
 */
export interface RepeatTaskRequest {
    /**
     * 
     * @type {boolean}
     * @memberof RepeatTaskRequest
     */
    force: boolean;
}

/**
 * Check if a given object implements the RepeatTaskRequest interface.
 */
export function instanceOfRepeatTaskRequest(value: object): value is RepeatTaskRequest {
    if (!('force' in value) || value['force'] === undefined) return false;
    return true;
}

export function RepeatTaskRequestFromJSON(json: any): RepeatTaskRequest {
    return RepeatTaskRequestFromJSONTyped(json, false);
}

export function RepeatTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepeatTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'force': json['force'],
    };
}

export function RepeatTaskRequestToJSON(json: any): RepeatTaskRequest {
    return RepeatTaskRequestToJSONTyped(json, false);
}

export function RepeatTaskRequestToJSONTyped(value?: RepeatTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'force': value['force'],
    };
}

