/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceRevision
 */
export interface ServiceRevision {
    /**
     * 
     * @type {number}
     * @memberof ServiceRevision
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceRevision
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceRevision
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceRevision
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceRevision
     */
    external: boolean;
    /**
     * 
     * @type {number}
     * @memberof ServiceRevision
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceRevision
     */
    version: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceRevision
     */
    serviceId: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ServiceRevision
     */
    manifest?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof ServiceRevision
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ServiceRevision interface.
 */
export function instanceOfServiceRevision(value: object): value is ServiceRevision {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('external' in value) || value['external'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ServiceRevisionFromJSON(json: any): ServiceRevision {
    return ServiceRevisionFromJSONTyped(json, false);
}

export function ServiceRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'type': json['type'],
        'external': json['external'],
        'number': json['number'],
        'version': json['version'],
        'serviceId': json['serviceId'],
        'manifest': json['manifest'] == null ? undefined : json['manifest'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ServiceRevisionToJSON(json: any): ServiceRevision {
    return ServiceRevisionToJSONTyped(json, false);
}

export function ServiceRevisionToJSONTyped(value?: ServiceRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'type': value['type'],
        'external': value['external'],
        'number': value['number'],
        'version': value['version'],
        'serviceId': value['serviceId'],
        'manifest': value['manifest'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

