/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StackAutoUpdatePolicy } from './StackAutoUpdatePolicy';
import {
    StackAutoUpdatePolicyFromJSON,
    StackAutoUpdatePolicyFromJSONTyped,
    StackAutoUpdatePolicyToJSON,
    StackAutoUpdatePolicyToJSONTyped,
} from './StackAutoUpdatePolicy';

/**
 * 
 * @export
 * @interface StackAutoServiceRevisionUpdateSettings
 */
export interface StackAutoServiceRevisionUpdateSettings {
    /**
     * 
     * @type {boolean}
     * @memberof StackAutoServiceRevisionUpdateSettings
     */
    enabled: boolean;
    /**
     * 
     * @type {StackAutoUpdatePolicy}
     * @memberof StackAutoServiceRevisionUpdateSettings
     */
    policy?: StackAutoUpdatePolicy;
}

/**
 * Check if a given object implements the StackAutoServiceRevisionUpdateSettings interface.
 */
export function instanceOfStackAutoServiceRevisionUpdateSettings(value: object): value is StackAutoServiceRevisionUpdateSettings {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function StackAutoServiceRevisionUpdateSettingsFromJSON(json: any): StackAutoServiceRevisionUpdateSettings {
    return StackAutoServiceRevisionUpdateSettingsFromJSONTyped(json, false);
}

export function StackAutoServiceRevisionUpdateSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StackAutoServiceRevisionUpdateSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'policy': json['policy'] == null ? undefined : StackAutoUpdatePolicyFromJSON(json['policy']),
    };
}

export function StackAutoServiceRevisionUpdateSettingsToJSON(json: any): StackAutoServiceRevisionUpdateSettings {
    return StackAutoServiceRevisionUpdateSettingsToJSONTyped(json, false);
}

export function StackAutoServiceRevisionUpdateSettingsToJSONTyped(value?: StackAutoServiceRevisionUpdateSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'policy': StackAutoUpdatePolicyToJSON(value['policy']),
    };
}

