/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StackAutoOriginUpdateSettingsInput } from './StackAutoOriginUpdateSettingsInput';
import {
    StackAutoOriginUpdateSettingsInputFromJSON,
    StackAutoOriginUpdateSettingsInputFromJSONTyped,
    StackAutoOriginUpdateSettingsInputToJSON,
    StackAutoOriginUpdateSettingsInputToJSONTyped,
} from './StackAutoOriginUpdateSettingsInput';
import type { StackAutoServiceRevisionUpdateSettingsInput } from './StackAutoServiceRevisionUpdateSettingsInput';
import {
    StackAutoServiceRevisionUpdateSettingsInputFromJSON,
    StackAutoServiceRevisionUpdateSettingsInputFromJSONTyped,
    StackAutoServiceRevisionUpdateSettingsInputToJSON,
    StackAutoServiceRevisionUpdateSettingsInputToJSONTyped,
} from './StackAutoServiceRevisionUpdateSettingsInput';
import type { GitAutoUpdateSettingsInput } from './GitAutoUpdateSettingsInput';
import {
    GitAutoUpdateSettingsInputFromJSON,
    GitAutoUpdateSettingsInputFromJSONTyped,
    GitAutoUpdateSettingsInputToJSON,
    GitAutoUpdateSettingsInputToJSONTyped,
} from './GitAutoUpdateSettingsInput';

/**
 * 
 * @export
 * @interface StackSettingsInput
 */
export interface StackSettingsInput {
    /**
     * 
     * @type {GitAutoUpdateSettingsInput}
     * @memberof StackSettingsInput
     */
    gitAutoUpdate?: GitAutoUpdateSettingsInput;
    /**
     * 
     * @type {StackAutoServiceRevisionUpdateSettingsInput}
     * @memberof StackSettingsInput
     */
    autoServiceRevisionUpdate?: StackAutoServiceRevisionUpdateSettingsInput;
    /**
     * 
     * @type {StackAutoOriginUpdateSettingsInput}
     * @memberof StackSettingsInput
     */
    autoOriginStackUpdate?: StackAutoOriginUpdateSettingsInput;
}

/**
 * Check if a given object implements the StackSettingsInput interface.
 */
export function instanceOfStackSettingsInput(value: object): value is StackSettingsInput {
    return true;
}

export function StackSettingsInputFromJSON(json: any): StackSettingsInput {
    return StackSettingsInputFromJSONTyped(json, false);
}

export function StackSettingsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StackSettingsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'gitAutoUpdate': json['gitAutoUpdate'] == null ? undefined : GitAutoUpdateSettingsInputFromJSON(json['gitAutoUpdate']),
        'autoServiceRevisionUpdate': json['autoServiceRevisionUpdate'] == null ? undefined : StackAutoServiceRevisionUpdateSettingsInputFromJSON(json['autoServiceRevisionUpdate']),
        'autoOriginStackUpdate': json['autoOriginStackUpdate'] == null ? undefined : StackAutoOriginUpdateSettingsInputFromJSON(json['autoOriginStackUpdate']),
    };
}

export function StackSettingsInputToJSON(json: any): StackSettingsInput {
    return StackSettingsInputToJSONTyped(json, false);
}

export function StackSettingsInputToJSONTyped(value?: StackSettingsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gitAutoUpdate': GitAutoUpdateSettingsInputToJSON(value['gitAutoUpdate']),
        'autoServiceRevisionUpdate': StackAutoServiceRevisionUpdateSettingsInputToJSON(value['autoServiceRevisionUpdate']),
        'autoOriginStackUpdate': StackAutoOriginUpdateSettingsInputToJSON(value['autoOriginStackUpdate']),
    };
}

