/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StackServiceLink
 */
export interface StackServiceLink {
    /**
     * 
     * @type {number}
     * @memberof StackServiceLink
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof StackServiceLink
     */
    stackServiceId: number;
    /**
     * 
     * @type {number}
     * @memberof StackServiceLink
     */
    linkedStackServiceId: number;
    /**
     * 
     * @type {string}
     * @memberof StackServiceLink
     */
    name: string;
}

/**
 * Check if a given object implements the StackServiceLink interface.
 */
export function instanceOfStackServiceLink(value: object): value is StackServiceLink {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stackServiceId' in value) || value['stackServiceId'] === undefined) return false;
    if (!('linkedStackServiceId' in value) || value['linkedStackServiceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StackServiceLinkFromJSON(json: any): StackServiceLink {
    return StackServiceLinkFromJSONTyped(json, false);
}

export function StackServiceLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): StackServiceLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stackServiceId': json['stackServiceId'],
        'linkedStackServiceId': json['linkedStackServiceId'],
        'name': json['name'],
    };
}

export function StackServiceLinkToJSON(json: any): StackServiceLink {
    return StackServiceLinkToJSONTyped(json, false);
}

export function StackServiceLinkToJSONTyped(value?: StackServiceLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stackServiceId': value['stackServiceId'],
        'linkedStackServiceId': value['linkedStackServiceId'],
        'name': value['name'],
    };
}

