/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StackAutoUpdateVersionPolicyInput } from './StackAutoUpdateVersionPolicyInput';
import {
    StackAutoUpdateVersionPolicyInputFromJSON,
    StackAutoUpdateVersionPolicyInputFromJSONTyped,
    StackAutoUpdateVersionPolicyInputToJSON,
    StackAutoUpdateVersionPolicyInputToJSONTyped,
} from './StackAutoUpdateVersionPolicyInput';

/**
 * 
 * @export
 * @interface StackAutoUpdatePolicyInput
 */
export interface StackAutoUpdatePolicyInput {
    /**
     * 
     * @type {string}
     * @memberof StackAutoUpdatePolicyInput
     */
    scope?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StackAutoUpdatePolicyInput
     */
    includeDisabled?: boolean | null;
    /**
     * 
     * @type {StackAutoUpdateVersionPolicyInput}
     * @memberof StackAutoUpdatePolicyInput
     */
    versionPolicy?: StackAutoUpdateVersionPolicyInput;
}

/**
 * Check if a given object implements the StackAutoUpdatePolicyInput interface.
 */
export function instanceOfStackAutoUpdatePolicyInput(value: object): value is StackAutoUpdatePolicyInput {
    return true;
}

export function StackAutoUpdatePolicyInputFromJSON(json: any): StackAutoUpdatePolicyInput {
    return StackAutoUpdatePolicyInputFromJSONTyped(json, false);
}

export function StackAutoUpdatePolicyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StackAutoUpdatePolicyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'] == null ? undefined : json['scope'],
        'includeDisabled': json['includeDisabled'] == null ? undefined : json['includeDisabled'],
        'versionPolicy': json['versionPolicy'] == null ? undefined : StackAutoUpdateVersionPolicyInputFromJSON(json['versionPolicy']),
    };
}

export function StackAutoUpdatePolicyInputToJSON(json: any): StackAutoUpdatePolicyInput {
    return StackAutoUpdatePolicyInputToJSONTyped(json, false);
}

export function StackAutoUpdatePolicyInputToJSONTyped(value?: StackAutoUpdatePolicyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'includeDisabled': value['includeDisabled'],
        'versionPolicy': StackAutoUpdateVersionPolicyInputToJSON(value['versionPolicy']),
    };
}

