/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
    TaskToJSONTyped,
} from './Task';

/**
 * 
 * @export
 * @interface TasksResponse
 */
export interface TasksResponse {
    /**
     * 
     * @type {Array<Task>}
     * @memberof TasksResponse
     */
    items: Array<Task>;
    /**
     * 
     * @type {number}
     * @memberof TasksResponse
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof TasksResponse
     */
    nextPage?: number | null;
}

/**
 * Check if a given object implements the TasksResponse interface.
 */
export function instanceOfTasksResponse(value: object): value is TasksResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function TasksResponseFromJSON(json: any): TasksResponse {
    return TasksResponseFromJSONTyped(json, false);
}

export function TasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TaskFromJSON)),
        'totalCount': json['totalCount'],
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
    };
}

export function TasksResponseToJSON(json: any): TasksResponse {
    return TasksResponseToJSONTyped(json, false);
}

export function TasksResponseToJSONTyped(value?: TasksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TaskToJSON)),
        'totalCount': value['totalCount'],
        'nextPage': value['nextPage'],
    };
}

