/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskStep
 */
export interface TaskStep {
    /**
     * 
     * @type {number}
     * @memberof TaskStep
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TaskStep
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskStep
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof TaskStep
     */
    logStatus: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskStep
     */
    isSystem: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TaskStep
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskStep
     */
    endedAt?: Date | null;
}

/**
 * Check if a given object implements the TaskStep interface.
 */
export function instanceOfTaskStep(value: object): value is TaskStep {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('logStatus' in value) || value['logStatus'] === undefined) return false;
    if (!('isSystem' in value) || value['isSystem'] === undefined) return false;
    return true;
}

export function TaskStepFromJSON(json: any): TaskStep {
    return TaskStepFromJSONTyped(json, false);
}

export function TaskStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStep {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'status': json['status'],
        'logStatus': json['logStatus'],
        'isSystem': json['isSystem'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
    };
}

export function TaskStepToJSON(json: any): TaskStep {
    return TaskStepToJSONTyped(json, false);
}

export function TaskStepToJSONTyped(value?: TaskStep | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'logStatus': value['logStatus'],
        'isSystem': value['isSystem'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt'] as any).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt'] as any).toISOString()),
    };
}

