/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectInput
 */
export interface UpdateProjectInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectInput
     */
    title: string;
}

/**
 * Check if a given object implements the UpdateProjectInput interface.
 */
export function instanceOfUpdateProjectInput(value: object): value is UpdateProjectInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UpdateProjectInputFromJSON(json: any): UpdateProjectInput {
    return UpdateProjectInputFromJSONTyped(json, false);
}

export function UpdateProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function UpdateProjectInputToJSON(json: any): UpdateProjectInput {
    return UpdateProjectInputToJSONTyped(json, false);
}

export function UpdateProjectInputToJSONTyped(value?: UpdateProjectInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

