/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldInput } from './FieldInput';
import {
    FieldInputFromJSON,
    FieldInputFromJSONTyped,
    FieldInputToJSON,
    FieldInputToJSONTyped,
} from './FieldInput';

/**
 * 
 * @export
 * @interface UpdateIntegrationInput
 */
export interface UpdateIntegrationInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateIntegrationInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateIntegrationInput
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateIntegrationInput
     */
    kinds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateIntegrationInput
     */
    scope?: string | null;
    /**
     * 
     * @type {Array<FieldInput>}
     * @memberof UpdateIntegrationInput
     */
    fieldsInput?: Array<FieldInput>;
}

/**
 * Check if a given object implements the UpdateIntegrationInput interface.
 */
export function instanceOfUpdateIntegrationInput(value: object): value is UpdateIntegrationInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kinds' in value) || value['kinds'] === undefined) return false;
    return true;
}

export function UpdateIntegrationInputFromJSON(json: any): UpdateIntegrationInput {
    return UpdateIntegrationInputFromJSONTyped(json, false);
}

export function UpdateIntegrationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIntegrationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'name': json['name'],
        'kinds': json['kinds'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'fieldsInput': json['fieldsInput'] == null ? undefined : ((json['fieldsInput'] as Array<any>).map(FieldInputFromJSON)),
    };
}

export function UpdateIntegrationInputToJSON(json: any): UpdateIntegrationInput {
    return UpdateIntegrationInputToJSONTyped(json, false);
}

export function UpdateIntegrationInputToJSONTyped(value?: UpdateIntegrationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'name': value['name'],
        'kinds': value['kinds'],
        'scope': value['scope'],
        'fieldsInput': value['fieldsInput'] == null ? undefined : ((value['fieldsInput'] as Array<any>).map(FieldInputToJSON)),
    };
}

