/* tslint:disable */
/* eslint-disable */
/**
 * Wodby 2.0 Public API
 * Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VolumeSizeInput
 */
export interface VolumeSizeInput {
    /**
     * 
     * @type {string}
     * @memberof VolumeSizeInput
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof VolumeSizeInput
     */
    size: number;
}

/**
 * Check if a given object implements the VolumeSizeInput interface.
 */
export function instanceOfVolumeSizeInput(value: object): value is VolumeSizeInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function VolumeSizeInputFromJSON(json: any): VolumeSizeInput {
    return VolumeSizeInputFromJSONTyped(json, false);
}

export function VolumeSizeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeSizeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'size': json['size'],
    };
}

export function VolumeSizeInputToJSON(json: any): VolumeSizeInput {
    return VolumeSizeInputToJSONTyped(json, false);
}

export function VolumeSizeInputToJSONTyped(value?: VolumeSizeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'size': value['size'],
    };
}

